### ISSUE TITLE
Mandatory field in blocks can be empty

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu#3185] opened 2017-02-07 16:30 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.5
| Browser Version | everyone

#### Actual Behavior

If you have blocks with mandatory field for each block-item and you don't fill it, you can save the page - without an error.

#### Expected Behavior

An error should be shown that the mandatory field should be filled or can't be empty.

#### Steps to Reproduce

Create blocks in xml template
Create a field with the property attribute `mandatory="true"`
Go to sulu admin and choose the block.
Try to save the page - without fill something in the field with the attribute mandatory.

![bildschirmfoto 2017-02-07 um 16 54 02](https://cloud.githubusercontent.com/assets/8446518/22700482/25653dfc-ed5b-11e6-9f2a-392a564799ee.png)

**Comment by danrot** [comment] 2017-02-07 16:32
Sorry, just saw that there already is an issue for that... So I am closing it as a duplicate of #3161

**Closed by danrot** 2017-02-07 16:32 UTC
