### ISSUE TITLE
Create snippet/page: No error displayed when default template does not exist

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#711] opened 2015-01-14 09:33 UTC
If the configured default template for a page/snippet does not exist and you try and create a new snippet/page then the server will respond with a 500 error.

This is correct, however the 500 is not handled by the application. It should display a red banner on all 500 responses as defined in: `AdminBundle/Resources/js/components/app/main.js`

**Comment by danrot** [comment] 2019-11-21 16:04
Closing as duplicate of #3417

**Closed by danrot** 2019-11-21 16:04 UTC
Labels: Bug, DX, Easy Pick
