### ISSUE TITLE
Missing parent url on children page when creating parent after

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1776] opened 2015-11-12 09:03 UTC
Steps to create the issue

1. Create a parent page in DE
2. Create a child page in EN (e.g. url. /child)
3. Create the EN parent page (e.g. url /parent)

Now the child page should be `/parent/child` but still is `/child`

**Comment by danrot** [comment] 2015-12-02 10:01
Related to #433

**Comment by danrot** [comment] 2016-02-22 13:30
Can't reproduce this bug ATM, because it seems like creating a child page of a ghost is currently not possible at all. If you try it, there is no save request sent, and the loader does not appear.

**Comment by danrot** [comment] 2016-03-29 12:38
I was trying to reproduce the bug again, and I don't know what was happening when this issue was created. The problem is that if you try to create a child of a ghost page, the system doesn't know how to build the URL. So you can't even save a page like this. The question is more if this should be possible.

**Comment by danrot** [comment] 2016-03-30 06:53
In a discussion with @chirimoya we decided that the URL should be generated as it was previously (just skip the ghost pages in the URL generation process). But then a ghost page has to change all of its children's URLs, once an actual page with an URL is generated from it.

**Comment by danrot** [comment] 2016-03-31 14:52
Step 1 and 2 do not work if the child page is not saved in between, because the generation of the route is failing then (and the save button also can't be clicked, but I am not sure by what that is caused...)

**Comment by danrot** [comment] 2016-07-20 11:57
The steps described here are working now, but the problem has moved to draft pages. If you have a page which has not been published yet, it is not a ghost page, but also has no URL. So if a child of a non-published page will be created, the generation does not work, but fails with a `ResourceLocatorNotFoundException`.

**Comment by danrot** [comment] 2016-07-21 06:11
Duplicate of #2646

**Closed by danrot** 2016-07-21 06:11 UTC
Labels: Bug
