### ISSUE TITLE
Bug when cropping images

### ISSUE THREAD

**Issue by roykoper** [sulu/sulu#5318] opened 2020-06-03 08:40 UTC
| Q | A
| --- | ---
| Sulu Version | 2.0.7
| Browser Version | Google Chrome 81.0.4044.138

# Actual Behavior

Here's a video to demonstrate how it's currently behaving

![SuluCropBug](https://user-images.githubusercontent.com/39400442/83614437-7c211e00-a585-11ea-96dd-d07216009cec.gif)

There's 2 issues here:
1. When changing the format, the resize window does not change until after trying to drag it.
2. It's not possible to drag the resize window to the right

# Expected Behavior

1. The resize window should change after selecting a format, not after dragging the resize window.
2. To be able to drag the resize window to the right

# Steps to Reproduce

1. Upload an image

2. Create a new image format with a higher width/height than the initial image

```
    <format key="format">
        <meta>
            <title lang="nl, en">(420x720px)</title>
        </meta>
        <scale x="420" y="720"/>

        <options>
            <option name="jpeg_quality">80</option>
            <option name="png_compression_level">6</option>
        </options>
    </format>
```

3. Choose the image format when cropping
4. Observe

# Possible Solutions

In the demonstration video I've used a 500x500px image, when selecting an image with a higher width/height the issue occurs, but when using a smaller width/height than the initial image it is working as expected.

**Comment by danrot** [comment] 2020-06-17 11:05
This feels like a duplicate of #5155, and I've thought I have fixed that in #5197... That should already be contained in 2.0.7. Are you sure you have that latest version installed? And can you make sure that you have the latest admin build by executing `bin/console sulu:admin:download-build`? It should actually work afterwards.

**Comment by danrot** [comment] 2020-06-26 06:15
Closing this issue due to inactivity.

**Closed by danrot** 2020-06-26 06:15 UTC
Labels: Bug, Needs Information

**Comment by roykoper** [comment] 2020-07-02 13:03
Reopening this issue as I'm able to reproduce it 100%.
I've installed a new project of Sulu following the steps of the Getting Started(https://docs.sulu.io/en/2.0/book/getting-started.html)
This installs the newest version(2.1.0)

Now following the Steps to Reproduce I'm running into the issue as described above.

**Comment by danrot** [comment] 2020-07-13 08:42
I have just tried, and I can move the crop to the very right when I try it. Can you maybe add an image, with which this error is happening?
