### ISSUE TITLE
Folder Sulu\Bundle\AdminBundle\Navigation was deleted since release 2.0.0

### ISSUE THREAD

**Issue by agazzi** [sulu/sulu#5085] opened 2020-03-02 10:07 UTC
Hello,

After seeing documentation for creating new admin feature, i noticed that the support for the navigation feature in the backoffice sidebar section does not work.

After investigation, navigation folder localized at Sulu\Bundle\AdminBundle\Navigation was deleted since the Sulu stable release 2.0.0.

Now the question is, everything is okay and documentation is not up to date or is a regress/bug ?

Thank you for helping

Regards
William R.

**Comment by alexander-schranz** [comment] 2020-03-02 10:16
@agazzi to which docs are you linking?
In https://docs.sulu.io/en/2.0/book/extend-admin.html the new Namespaces are used:

```php
use Sulu\Bundle\AdminBundle\Admin\Navigation\NavigationItem;
use Sulu\Bundle\AdminBundle\Admin\Navigation\NavigationItemCollection;
```

**Comment by alexander-schranz** [comment] 2020-03-12 17:10
Closing because not reproducable feel free to add comment here again would be interesting where this is falsly documented.

**Closed by alexander-schranz** 2020-03-12 17:10 UTC
Labels: Bug
