### ISSUE TITLE
Editing a page with insufficient permissions results in error message: Operation forbidden 

### ISSUE THREAD

**Issue by reflexxion** [sulu/sulu#2911] opened 2016-09-08 07:58 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3

#### Actual Behavior

When a user tries to access the backend administration of a page without having role  ``sulu.security.users``.``view`` the **Operation forbidden** message is shown.

The backend is trying to access ``/admin/api/users/[ID]`` for displaying the users name in e.g. the changelog.

#### Expected Behavior

Don't show an error.

#### Steps to Reproduce

Create a new users and don't grant ``sulu.security.users``.``view``. Then edit an exisiting page.

#### Possible Solutions

* Hide changelog, etc. for users without sufficient permissions
* Do not show an error message
* Add some other permission for changelog etc.

**Comment by danrot** [comment] 2016-09-19 06:43
That's actually the same issue as https://github.com/sulu/sulu/issues/1482.

**Comment by danrot** [comment] 2016-09-19 12:13
Closing as duplicate of #1482

**Closed by danrot** 2016-09-19 12:13 UTC
Labels: Duplicate
