### ISSUE TITLE
[Versioning] Restoring page version breaks child pages

### ISSUE THREAD

**Issue by amb-jarek** [sulu/sulu#5550] opened 2020-10-14 09:13 UTC
| Q | A
| --- | ---
| Sulu Version | 2.1
| Browser Version | Not relevant

# Actual Behavior

Restoring page version of the parent page breaks child pages which were also restored at some point of time

# Expected Behavior

Restoring any page shoult not have impact on child pages

# Steps to Reproduce
tested on https://sulu.rocks/
![image](https://user-images.githubusercontent.com/38923701/95968846-3f581400-0e0e-11eb-9ac3-7be29274839e.png)

- edit "Coyoos" (child) page three times - to generate three versions
- restore second version - everything is fine, page successfully restored
- edit "Artist" (parent) page three times - to generate three versions
- restore second version - page seems to be restored successfully but child page "Coyoos" is broken as marked on screen above

**Comment by niklasnatter** [comment] 2021-03-22 11:56
Just tried to reproduce this - I think it is not necessary to restore the child page. It looks like restoring a page to version B will break all child pages that had a draft at the time when version B was snapshotted. The following steps are enough to reproduce this for me:

1. Change `Coyoos` to `Coyoos2` and save as draft
2. Change `Artist` to `Artist2` and save and publish 
3. Change `Artist2` to `Artist3` and save and publish 
4. Restore second version of `Artist3` (should restore `Artist2`)

**Comment by nnatter** [comment] 2021-03-22 12:13
Spent some more time on this. It looks like this not only affects child pages with a draft, but also fully published child pages that have a descendant (child, grandchild, ...) with a draft. This reproduces the problem too:

1. Create a new `Bob Dylan` page as child of `Artist` and publish it
2. Create a new `Test` page as child of the `Bob Dylan` page and **save as draft**
3. Change `Artist` to `Artist2` and save and publish 
4. Change `Artist2` to `Artist3` and save and publish 
5. Restore second version of `Artist3` (should restore `Artist2`)

**Comment by niklasnatter** [comment] 2021-03-22 16:25
Spent some more time on this. I dont think the problem is related to draft pages anymore. It looks like restoring a page to version B will **break all child pages that had at least one version at the time when version B was snapshotted**.
I can reproduce the problem with the following steps:

1. Create and publish a `Parent` page
2. Create and publish a `Child` page
3. Rename and publish the `Parent` page to `Parent2`
4. Rename and publish the `Parent2` page to `Parent3`
5. Restore the second version of the `Parent3` page (should restore to `Parent2`)

On a sidenote: The problem does not occur for existing pages on `sulu.rocks` because we restore the existing pages from a backup and therefore they do not have a version initially.

**Comment by niklasnatter** [comment] 2021-03-26 08:21
Thanks for reporting! Fixed by #5895

**Closed by niklasnatter** 2021-03-26 08:21 UTC
Labels: Bug
