### ISSUE TITLE
Crash on MariaDB because of reserved keyword in query

### ISSUE THREAD

**Issue by danakil** [sulu/sulu#6412] opened 2021-12-07 17:47 UTC
| Q | A
| --- | ---
| Sulu Version | 2.3.7
| PHP Version | 7.4.26
| DB Version | 10.3.32-MariaDB-0ubuntu0.20.04.1 - Ubuntu 20.04
| Browser Version | Brave

# Actual Behavior

Sulu crash on pages using the permission system (error 500) on some versions of MariaDB.
It seems to be related to the usage of the reserved keyword "system" in Sulu\Bundle\SecurityBundle\Entity\RoleRepository.
This page https://mariadb.com/kb/en/reserved-words/#oracle-mode says that "system" is a reserved keyword in the "Oracle mode" section. 
`SYSTEM: <= MariaDB 10.3.6 only. Note however that SYSTEM sometimes needs to be quoted to avoid confusion with System-versioned tables.`

I'm not sure what is this oracle mode, my db settings are as follow:
`DATABASE_URL=mysql://root:root@mysql:3306/xxx?serverVersion=mariadb-10.3.32`

# Expected Behavior

It should'nt crash :)

# Steps to Reproduce

Activate the permission system on some page.
Use an affected version of MariaDb
Try to access to these pages through the website or the admin

Note: my local install (docker stack) has this version of MariaDb:
`10.3.25-MariaDB-1:10.3.25+maria~focal - mariadb.org binary distribution`
I can't explain why but it works without problem here although it should be affected if the problem is related to the reserved keywords and the MariaDb version.

# Possible Solutions

No idea if this is a proper fix but I can workaround the crash by changing the queries in Sulu\Bundle\SecurityBundle\Entity\RoleRepository

Original code:

```php
public function findRoleIdsBySystem($system)
    {
        $result = $this->createQueryBuilder('role')
            ->select('role.id')
            ->where('role.system = :system')
            ->setParameter('system', $system)
            ->getQuery()
            ->getResult();

        return \array_map(function($role) {
            return $role['id'];
        }, $result);
    }

```

Updated code (I just changed the parameter name "system" to "systemRenamed"):

```php
public function findRoleIdsBySystem($system)
    {
        $result = $this->createQueryBuilder('role')
            ->select('role.id')
            ->where('role.system = :systemRenamed')
            ->setParameter('systemRenamed', $system)
            ->getQuery()
            ->getResult();

        return \array_map(function($role) {
            return $role['id'];
        }, $result);
    }
```

The findAllRoles() method has a "system" parameter too, I suppose it could lead to a crash but I've not changed it.
Note that I have no idea if other parts of the code are affected by this change.

**Comment by danakil** [comment] 2021-12-07 17:58
Note that the string "->setParameter('system'" appears in multiples files when I search it in my vendors (all the occurences are on Sulu related files only). I suppose that the problem might affect all theses files.

**Comment by alexander-schranz** [comment] 2021-12-07 18:28
@danakil are you sure you are using Sulu 2.3.7? Because the `system` keyword was already resolved by renaming the column to `securitySystem` in  Sulu Version `>=2.0.0` here https://github.com/sulu/sulu/pull/4687

**Comment by alexander-schranz** [comment] 2021-12-07 18:30
Can you tell us which version of `doctrine/dbal` and `doctrine/orm` is used in your case? ~~And how your DATABASE_URL for maria db looks like?~~ EDIT: sorry you already provided that.

**Comment by alexander-schranz** [comment] 2021-12-07 21:40
I setup mariadb and also did run our tests again mariadb in https://github.com/sulu/sulu/pull/6415 but I could not reproduce the problem with RESERVED Keyword system there. The queryBuilder normally works with the `fieldName` and dbal will correctly use then the `columnName` of the field and so a SQL query should never have the reserved keyword `SYSTEM` in it. Maybe there was an error in dbal which is already fixed can you try update the doctrine packages to the latest version and check if the error still appear there?

Want to mention Sulu 1.6 does not support MySQL 8 or equivalent version of MariaDB.

**Comment by danakil** [comment] 2021-12-08 09:08
Hi Alexander,
Thank you for your time ! I can't explain this behaviour and I hope I'm not doing anything wrong. Here are some more informations.

LOCAL DEV (docker stack):
Database: 10.3.25-MariaDB-1:10.3.25+maria~focal - mariadb.org binary distribution [mysql via TCP/IP]
PHP: 7.4.5

PRODUCTION:
Database: 10.3.32-MariaDB-0ubuntu0.20.04.1 - Ubuntu 20.04 [Localhost via UNIX socket]
PHP: 7.4.26
The server is an up to date Plesk based server. Tried FPM or Apache FastCGI.

My vendors are pretty up to date [SF 5.3.10 / Sulu 2.3.7]. You can find the composer.json used when I first encountered the crash attached.
[composer.txt](https://github.com/sulu/sulu/files/7674654/composer.txt)
I nonetheless updated all my vendors and I'm now on SF 5.4.0 / Sulu 2.3.7], but I didn't change anything.

On local dev, all is working fine, with APP_ENV on dev or prod.
I uploaded all my sources and database to my production server, cleared all the cache and I have no diff to update in the db schema.

On the production server, the website and the admin seems OK unless I access a page with permissions (crash with no logs on the website and the UI won't load in the admin).
With APP_ENV dev on the production server, the protected pages are working.
If I switch to APP_ENV prod, the protected pages are working only on the first load if the cache is empty (cleared with rm -rf).
As soon as I refresh the page, it crash again, until I clear the cache.
Note that if I check the query log in APP_ENV dev, the query fetching the roles is "SELECT s0_.id AS id_0 FROM se_roles s0_ WHERE s0_.securitySystem = ?".

If I replace the parameter name "system" with "systemRenamed" in RoleRepository::findRoleIdsBySystem(), all is working fine in dev or prod.

**Comment by danakil** [comment] 2021-12-08 09:33
The quey `SELECT * FROM mysql.help_keyword;` should (?) display the list of reserved keywords.
I ran this query on both my local docker db and on my production server and the "SYSTEM" keyword is not there (464 results on both environments). I'm lost...

**Comment by alexander-schranz** [comment] 2021-12-08 11:49
Thanks for the response. It is really strange. Can you share the `composer.lock` and the output of the `composer info`? The `composer.json` does not represent which version are installed. Best if its directly the lock which and info output from the production server.

**Comment by danakil** [comment] 2021-12-08 12:05
Here are my composer infos:
[20211208_1300_composer_info.txt](https://github.com/sulu/sulu/files/7675853/20211208_1300_composer_info.txt)
[20211208_1300_composer.lock.txt](https://github.com/sulu/sulu/files/7675854/20211208_1300_composer.lock.txt)
Please note that altought I ran the "composer info" on the production server, I didn't installed the vendors by running composer from the server. All my sources, including vendors and database are directly copied from my local dev to my server. Maybe not the best method but I never had any problem...

**Comment by danakil** [comment] 2021-12-08 12:17
I just removed all my vendor directory and composer.lock file from the production server and installed the vendors directly from the server (composer install). Still the same problem. Here are the updated composer infos:

[20211208_1313_from_server_composer_info.txt](https://github.com/sulu/sulu/files/7675924/20211208_1313_from_server_composer_info.txt)

[20211208_1313_from_server_composer_lock.txt](https://github.com/sulu/sulu/files/7675925/20211208_1313_from_server_composer_lock.txt)

**Comment by alexander-schranz** [comment] 2021-12-08 12:35
Thank you. Looks all correct from point of view. Would really like to find out how we could reproduce it to know if the problem is here on our side or on doctrine side.

Can you run the following SQL queries once on your local system and once prod to check what the difference is there and tell us them here:

```bash
bin/console doctrine:query:sql "SELECT @@VERSION"
bin/console doctrine:query:sql "SELECT @@SQL_MODE"
```

Also check if the result represent what the `DATABASE_URL` is configured to:

```bash
bin/console debug:container --env-var  DATABASE_URL
```

It could also be that `doctrine/dbal` does not really support running `mariadb` in the `oracle` mode. 

Another interesting thing would be if this happens only with `doctrine/dbal` `3`. Could you check if you require `doctrine/dbal:2` if it works then:

```bash
composer require doctrine/dbal:"^2"

# sometimes composer blocks downgrades so you need todo it with:
#
# composer require doctrine/dbal:"^2" --no-update
# composer update
```

**Comment by danakil** [comment] 2021-12-08 13:06
LOCAL (DOCKER STACK)

root@63a4d26b428f:/home/wwwroot/xxx/front# bin/console doctrine:query:sql "SELECT @@VERSION"
[WARNING] This command will be executed in the "admin" context. For the "website" context, run ./bin/websiteconsole    
array(1) {
  [0]=>
  array(1) {
    ["@@VERSION"]=>
    string(37) "10.3.25-MariaDB-1:10.3.25+maria~focal"
  }
}

root@63a4d26b428f:/home/wwwroot/xxx/front# bin/console doctrine:query:sql "SELECT @@SQL_MODE"
[WARNING] This command will be executed in the "admin" context. For the "website" context, run ./bin/websiteconsole    
array(1) {
  [0]=>
  array(1) {
    ["@@SQL_MODE"]=>
    string(89) "STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
  }
}



PRODUCTION

xxx@plesk:~/httpdocs/front$ php bin/console doctrine:query:sql "SELECT @@VERSION"
[WARNING] This command will be executed in the "admin" context. For the "website" context, run ./bin/websiteconsole    
array(1) {
  [0]=>
  array(1) {
    ["@@VERSION"]=>
    string(32) "10.3.32-MariaDB-0ubuntu0.20.04.1"
  }
}

xxx@plesk:~/httpdocs/front$ php bin/console doctrine:query:sql "SELECT @@SQL_MODE"
[WARNING] This command will be executed in the "admin" context. For the "website" context, run ./bin/websiteconsole    
array(1) {
  [0]=>
  array(1) {
    ["@@SQL_MODE"]=>
    string(69) "ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
  }
}


About "Also check if the result represent what the DATABASE_URL is configured to" [bin/console debug:container --env-var DATABASE_URL]

Please note that I use a "env.local" on both my local dev and my production server to store sensible values, but it shouldn't change anything.

LOCAL (DOCKER STACK): DATABASE_URL matches with my .env settings
PRODUCTION: well, I don't understand why but the command outputs "None of the environment variables match this name" on the production server. But it works just fine with "php bin/websiteconsole debug:dotenv"
    and the DATABASE_URL matches with my .env settings.

I will try do downgrade the dbal now.

**Comment by danakil** [comment] 2021-12-08 13:14
So I downgraded the dbal from 3 to 2 on the production server:
  - Downgrading doctrine/dbal (3.2.0 => 2.13.6)
Then cleared manually the cache (rm -rf)

Stil the same behavior (works on first page load but crash on a refresh).

[20211208_1411_composer_lock_downgraded_to_dbal_2.txt](https://github.com/sulu/sulu/files/7676206/20211208_1411_composer_lock_downgraded_to_dbal_2.txt)

I really hope it's nothing wrong on my side but I can't find anything.

**Comment by alexander-schranz** [comment] 2021-12-10 12:35
@danakil can you reproduce it locally when you set mariadb locally to the same SQL_MODE as it is online?

**Comment by danakil** [comment] 2021-12-13 15:25
Hi Alexander, sorry for the delay.
I tried to set the same sql_mode string on my local dev server but I can't reproduce the crash. My docker env and my production server are pretty close and I can't find what could trigger the error on prod sorry :(

But I think the error is still related to the reserved keywords, I just have no idea why it appears only on my production server.
See this bug report for example: https://github.com/doctrine/dbal/issues/3152. It's for the DBAL and not the ORM but the root cause may be the same. If you search for "reserved keyword" in the Doctrine ORM or DBAL issues, you can find many related issues.

Maybe I can override RoleRepository (is this possible ?) and rename this parameter myself as a temporary workaround ?
If you have any hint or other possible workaround...

And why mysql use so commonly used words as reserved keywords !!

**Comment by alexander-schranz** [comment] 2021-12-13 15:39
@danakil thx for the reply we are not using reserved keywords in the query itself. The `setParameter` you mention is something which normally never get used in the generate SQL. `$queryBuilder->getQuery->getSQL()`. We can rename `:system` to `:roleSystem` (can you create a PR for this) but would be great to cover this kind of errors in future over tests.
Do you setup the production server yourself or can ask the hoster what kind of mariadb changes they use which could trigger this error, so we can test again that configuration to find maybe other errors?

**Comment by alexander-schranz** [comment] 2021-12-13 15:47
@danakil did you tried it locally also in the `prod` env. Maybe doctrine behaves differently between dev and prod?

**Comment by danakil** [comment] 2021-12-13 16:05
@alexander-schranz I tried both with dev and prod env.

Yes, I understand that "system" should not and don't appear in the generated SQL. If I dump getQuery()->getSQL(), I get
`"SELECT s0_.id AS id_0 FROM se_roles s0_ WHERE s0_.securitySystem = ?"`
But there is definitely something wrong somewhere...

Note that "system" should be a reserved keyword on mariadb only with the "ORACLE" mode enabled. 
[https://mariadb.com/kb/en/reserved-words/#oracle-mode](url)
I don't see this "ORACLE" option enabled on my server (but according to [https://mariadb.com/kb/en/sql_modeoracle/](url), it is an alias for a set of modes. I tried to activate the ORACLE mode on my local dev but it leads to some unrelated crashes:
`An exception has been thrown during the rendering of a template ("An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column '2' in 'where clause'").`
while rendering a template: `{% for nav_item in sulu_navigation_root_tree('main', 1) %}`

Note that the doc says that "system" is a reserved keyword on <= MariaDB 10.3.6 only (and I'm on 10.3.25 and 10.3.32).
And that the only apparent difference between my sql_modes dev/prod are the STRICT_TRANS_TABLES which seems not really related to me but I may be wrong.

My server is self managed OVH server based on a OVH image with Plesk (Ubuntu 20.04.1 LTS). It should be pretty up to date and close to the defaults. We have plenty of websites on production and have no problems.

I must confess that I'm not very confortable with github, the PR and so on. I only have a basic usage of Git for myself...

**Comment by alexander-schranz** [comment] 2021-12-13 16:26
OVH is your hoster? Is this ovhcloud.com?

A pull request for your issue should be straight forward. You can just go to: https://github.com/sulu/sulu/blob/2.2/src/Sulu/Bundle/SecurityBundle/Entity/RoleRepository.php
Click "edit" do your changes and Github should automatically create a new fork and a new branch (patch-1) and should then allow you create a Pull Request against our 2.2 branch. If you need any help let me know.

**Comment by danakil** [comment] 2021-12-13 16:34
Yes, it's a dedicated server from OVH (ovhcloud indeed but it's just a standard server, not something "in the cloud").
Ubuntu 20.04.3 LTS, Plesk Obsidian and nightly updates. 
I will try the PR right now.

**Comment by danakil** [comment] 2021-12-13 16:44
Done, https://github.com/sulu/sulu/pull/6423
I'll be glad to be informed if you have any informations concerning this issue :)

**Comment by alexander-schranz** [comment] 2021-12-14 10:59
Thx for the pull request.

What also get into my mind that it maybe have todo with install php extensions can you show the [difference](https://www.diffchecker.com/). Between local and the server of the following commands output:

```php
php -r 'foreach(get_loaded_extensions() as $extension) { echo $extension . ": " . phpversion($extension) . PHP_EOL;};'
```

**Comment by alexander-schranz** [comment] 2021-12-14 11:33
#6423 is merged and will be part of the next release. Still the result of my last comment would be interesting maybe we found out a way how we could reproduce this issue then.

**Comment by danakil** [comment] 2021-12-15 11:48
Hi Alexander,
Thank you for the merge !

Here is a dump of my loaded php extensions.
[local_vs_prod_loaded_php_extensions.txt](https://github.com/sulu/sulu/files/7719026/local_vs_prod_loaded_php_extensions.txt)

**Comment by niklasnatter** [comment] 2022-01-13 13:14
With #6423 being merged, I will close this as solved. Please feel free to create a new issue if the problem pops up again!

**Closed as completed by niklasnatter** 2022-01-13 13:14 UTC
Labels: Bug

**Comment by alexander-schranz** [comment] 2022-01-13 13:26
@danakil sorry for the late response. I could not find anything out and how this issue is caused. I could not reproduce it but as niklas mention #6423 should fix your issue I hope we not get into another issue with this type of maria db setup.
