### ISSUE TITLE
Ghost page has no edit icon

### ISSUE THREAD

**Issue by thomasduenser** [sulu/sulu#2976] opened 2016-10-11 09:42 UTC
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3.1 |
#### Actual Behavior

The pencil icon is not visible for ghost pages in the backend content tree view. This is confusing as the icon was there before. Now the only possibility to interact with this page is a double click, which opens the overlay to create a new page in this language or copy the page content.
#### Expected Behavior

That the pencil icon is visible which opens the overlay.
#### Steps to Reproduce
1. Create a page in DE
2. Go back to the tree view
3. Change the language to EN
4. Hover over the page - no icon visible

DE Hover State
<img width="327" alt="bildschirmfoto 2016-10-11 um 11 34 58" src="https://cloud.githubusercontent.com/assets/3875917/19265958/c025550a-8fa7-11e6-82c7-9cdaeee16c96.png">

EN Hover State
<img width="325" alt="bildschirmfoto 2016-10-11 um 11 35 17" src="https://cloud.githubusercontent.com/assets/3875917/19265963/c34813da-8fa7-11e6-94b0-5e3fba10c951.png">

**Comment by danrot** [comment] 2016-11-10 09:47
Duplicate of #2847, and already fixed in #2855

**Closed by danrot** 2016-11-10 09:47 UTC
Labels: Duplicate
