### ISSUE TITLE
Webspaces not being added without hard deleting /var/cache

### ISSUE THREAD

**Issue by guttenbergovitz** [sulu/sulu#5309] opened 2020-05-29 10:32 UTC
Using **2.1.0-RC1**

# Actual Behavior

It seems Sulu is unable to discover new Webspaces without manually removing `var/cache` folder first.

# Expected Behavior

It would be lovely to avoid removing cache folder manually.

# Steps to Reproduce

After adding an XML with the new workspace definition to the operational Sulu instance following the docs instruction workspace is not being discovered  after:

`php bin/adminconsole cache:clear`
`php bin/adminconsole sulu:document:initialize`
`php bin/adminconsole sulu:content:validate:webspaces`

It seems one has to manually purge content of `var/cache` folder in order to let Sulu instance discover new Webspace. Tested on local host using `devilbox` & on Digital Ocean virtual droplet (Apache 2.2.41, PHP 7.4.3).

**Comment by alexander-schranz** [comment] 2020-05-29 10:38
@guttenbergovitz  Thank you for your report.

I can reproduce it. It seems like the cached WebsiteCollection class is not refreshed.

**Comment by danrot** [comment] 2020-06-02 04:56
The problem is the way Symfony handles this. It remembers all files that have been used to generate the cache and only updates if any of these files changed. If a new file is added, it is not part of this list, and therefore no cache clearing can happen automatically. Unless there is no specific suggestion on how to fix this, I would close this issue again, and redirect to #3132, because fully integrating that into the Symfony Config would allow to write all the webspaces in one file, and then the cache busting would work as expected.

**Comment by nnatter** [comment] 2020-06-02 12:33
I think its okay that the cache clearing does not happen automatically. But shouldnt the newly added webspace appear if I execute `php bin/adminconsole cache:clear `? 🤔

**Comment by danrot** [comment] 2020-06-04 07:51
Ah, I've misread that issue... Just tried it, and can confirm that this is happening, but I currently have no idea why :confused:

@guttenbergovitz How well do you know the `cache:clear` command? Might need some debugging to figure out what's going on... I bet it is somehow related to [this line in the `WebspaceManager`](https://github.com/sulu/sulu/blob/7fc5cac/src/Sulu/Component/Webspace/Manager/WebspaceManager.php#L373)... I just tried adding a new YAML file in `config/packages`, and that works. I guess that's because a [glob import is used for that](https://github.com/sulu/sulu/blob/f804e37/src/Sulu/Component/HttpKernel/SuluKernel.php#L82). So #3132 would probably solve this, but this is quite a big task. Maybe it is possible to do a smaller refactoring right now, that would make use of the glob syntax?

**Comment by alexander-schranz** [comment] 2020-06-04 07:59
@danrot the problem is that the cache component use in the webspace manager for `isFresh` does just check if the file exist. So something like we did for the system collection cache like here: https://github.com/sulu/sulu/blob/851fc5464886e8cee65e4d2ed523620e16b00a96/src/Sulu/Component/Media/SystemCollections/SystemCollectionManager.php#L79 is needed also for the webspace manager.

**Comment by danrot** [comment] 2020-06-04 09:11
While that might work, I feel like that defeats the purpose of the `cache:clear` command... This would simply always delete the webspace collection cache, although it might not be necessary.

But as a workaround that might be ok.

**Comment by danrot** [comment] 2020-09-29 11:42
Fixed in #5510

**Closed by danrot** 2020-09-29 11:42 UTC
Labels: Bug, DX
