### ISSUE TITLE
Manually edited url with slash is not fully editable after save

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1848] opened 2015-12-01 19:09 UTC
If I create a new page enter in the url e.g. `/en/test/page` I can only change the last part of the url(`page`) after save.

![bildschirmfoto 2015-12-01 um 20 09 18](https://cloud.githubusercontent.com/assets/1698337/11511111/70ff9a86-9867-11e5-9890-b0fb21a261b1.png)

![bildschirmfoto 2015-12-01 um 20 09 06](https://cloud.githubusercontent.com/assets/1698337/11511110/6ded7214-9867-11e5-9724-a06facbadb3b.png)

in my case the outputted url is now `/en/en/test/page`

**Comment by danrot** [comment] 2015-12-02 09:23
I guess the `/` should not be an allowed character in the URL.

**Comment by wachterjohannes** [comment] 2016-08-17 05:49
https://github.com/sulu/sulu/issues/2819

**Comment by danrot** [comment] 2016-08-23 07:52
Duplicate of #2819

**Closed by danrot** 2016-08-23 07:52 UTC
Labels: Bug
