### ISSUE TITLE
Media selection is mandatory but you can save and publish anyway

### ISSUE THREAD

**Issue by ReneZumtobel** [sulu/sulu#2901] opened 2016-09-05 14:53 UTC
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | dev-develop |
| Browser Version | Browser name and version |
#### Actual Behavior

It saved without a media selected.
#### Expected Behavior

It should not be possible to save and publish without selecting a media.
#### Steps to Reproduce

Add media content type to a template and make it mandatory. Then make a page of this type and save and publish it -> no error is shown.

**Comment by danrot** [comment] 2016-09-19 12:02
I guess that's because there is always some content delivered. When there are no images it will still deliver an object with a `displayPosition` value... We probably need some custom logic there 😕

**Comment by wachterjohannes** [comment] 2016-09-26 06:24
somehow related to https://github.com/sulu/sulu/issues/2938 i have also added there some thoughts about this.

    the usage of `minOccurs` (also `maxOccurs`) would be nice and i agree your thoughts about
    that. but with the `mandatory` i have a little problem because are multiple selected fields also
    valid (if mandatory) if no item is selected? `mandatory` was introduced originally to ensure that
    the value is not null and a empty array is also not null.

**Comment by danrot** [comment] 2017-03-06 06:41
Closing as duplicate of #2938

**Closed by danrot** 2017-03-06 06:41 UTC
Labels: Bug
