### ISSUE TITLE
Sulu auto scrolls to bottom of page

### ISSUE THREAD

**Issue by smanhoff** [sulu/sulu#5765] opened 2021-01-20 12:53 UTC
| Q | A
| --- | ---
| Sulu Version | 2.2.3 / 2.1.7
| PHP Version | 7.4.12
| Browser Version | Chrome 88.0.4324.96 (Official Build) (x86_64)

# Actual Behavior

While using longer lists and increasing the page limit to 100 for example, relevant results are showing while scrolling which is great. But when another tab in browser is openend and you return to Sulu tab it seems Sulu always scrolls down to the bottom of the page. Instead of staying at the top or same position the current user left it in.

The same for longer forms, after returning to the Sulu tab it's pointing at the bottom of the page.

This also seems to be the case in demo project, see [screencast](https://we.tl/t-CxfZWotKh6).

![screencast_sulu_scroll](https://user-images.githubusercontent.com/1698337/105179635-d9c0a580-5b29-11eb-8dd1-8c79846222fd.gif)

# Expected Behavior

Stay in same place where current user left it.

# Steps to Reproduce

Create a long list or long form for which you have to scroll. Stay on top of page and open new tab, return to previous tab and you wil notice Sulu scrolled to bottom of page incorrectly.

**Comment by alexander-schranz** [comment] 2021-01-20 13:15
@Sesamzaad I added the video as a gif so it don't get lost. Thank you for report. The behaviour is really strange, it seems also not always happening 🤔 .

**Comment by alexander-schranz** [comment] 2021-01-20 13:29
We could also reproduce this behaviour in a similar way on the `2.1.7` Version on focus lose.

**Comment by niklasnatter** [comment] 2021-01-20 13:38
Tested this a bit further - looks like this does not occur on `2.1.3`, but does occur on `2.1.4`. So the the reason should be somewhere in these changes: https://github.com/sulu/sulu/compare/2.1.3...2.1.4
From the first look, I would suspect https://github.com/sulu/sulu/pull/5567

**Comment by niklasnatter** [comment] 2021-01-26 11:59
Thanks a lot for reporting! Should be fixed in the next release by https://github.com/sulu/sulu/pull/5772

**Closed as completed by niklasnatter** 2021-01-26 11:59 UTC
Labels: Bug
