### ISSUE TITLE
unknown page status after restore version

### ISSUE THREAD

**Issue by jonland** [sulu/sulu#5890] opened 2021-03-22 12:28 UTC
| Q | A
| --- | ---
| Sulu Version | 2.2.3 with Jackrabbit
| Jackrabbit Version | 2.18.5
| PHP Version | 7.4.3
| DB Version | MySQL 8.0.23
| Browser Version | Chrome 89.0.4389.90

# Actual Behavior
1. Sulu 2.2 with Jackrabbit.
2. Edit top level element change to wrong page type.
3. Restoring previous version of page (page type changed)
4. child's status is unknown (draft, no content).

# Expected Behavior
Restore of parent page has no effect on child page(s).

# Steps to Reproduce
Create following structure of pages.
A (homepage) -> B (default) -> C (default)

1. now change A to type “default”, save and publish
2. restore A with version history, save and publish
3. go to content tree, B is marked with yellow dot and exclamation mark
4. edit B message is shown, content is empty

![sulu_issue_01](https://user-images.githubusercontent.com/6032820/111989714-6d0a5d00-8b12-11eb-83b3-2e6329340174.png)
![sulu_issue_02](https://user-images.githubusercontent.com/6032820/111989716-6e3b8a00-8b12-11eb-8d6f-9c4c05448c30.png)
![sulu_issue_03](https://user-images.githubusercontent.com/6032820/111989720-6ed42080-8b12-11eb-9228-fa304e2b2b98.png)

**Comment by niklasnatter** [comment] 2021-03-22 13:34
Hello,
thanks for creating this issue. Unfortunately, I am not able to reproduce the problem with the provided steps. 

https://user-images.githubusercontent.com/13310795/111997823-b7dca280-8b1b-11eb-81ca-809413f8b637.mov

- Can you please provide a screencast that shows how to reproduce the problem? 
- How are you running Jackrabbit?
- What was the status of the pages before executing the provided steps? Is it possible that one of the pages was not published (see https://github.com/sulu/sulu/issues/5550)?

**Comment by niklasnatter** [comment] 2021-03-22 16:31
After spending some more time on this, I found a way to reliably reproduce the problem. It think the problem is not related to changing the template. Instead, it looks like restoring a page to version B will break all child pages that had at least one version at the time when version B was snapshotted. 

I think this is the same problem as described in #5550, therefore I am going to close this issue. Thanks for reporting!

**Closed as completed by niklasnatter** 2021-03-22 16:31 UTC
Labels: Bug
