### ISSUE TITLE
sulu:build dev not creating the default admin user

### ISSUE THREAD

**Issue by kwinne** [sulu/sulu#6374] opened 2021-11-20 09:49 UTC
Hello,

I started a new project with Sulu 2.3.7 and executed the `php bin/adminconsole sulu:build dev`. Everything looks okay but the default admin user is not being created.
The log says: 
`
sulu:security:user:create  ({"username":"admin","firstName":"Adam","lastName":"Ministrator","email":"admin@example.com","locale":"en","role":"User","password":"admin"})
`
I have also tried executing the `bin/adminconsole sulu:security:user:create` manually but with the same result (no user in se_users and no contact).

**Comment by alexander-schranz** [comment] 2021-11-20 16:11
Hello @kwinne,

which webserver do you use? maybe you have a different database configured or something is is going wrong. Did you check if the database did create any data after you did purge it?
If you are using some special webserver setup it would best first try just the PHP internal websever with:

```
php -S localhost:8000 -t public/ config/router.php
```

And check then if you can login. Else as said above best is if you check if anything is created by the sulu:build command in your database, maybe try it with a new database name. Check if you really get a 401 on the POST Login request or maybe another errors happens? There could also be something written into the `var/log/admin/*.log` files which should give you a hint whats going wrong.

**Comment by kwinne** [comment] 2021-11-20 16:51
Hello,

I'm using Wamp as my server but the issue is before that I guess. The command creates the database just fine, even adds default data in some tables but the users table stays empty, there is not default admin user.

So I guess there is noting wrong with the connection itself. I cannot test out the POST login request because there is simply no user to test it with.

I just started a fresh project again, changed nothing but the DB connection and ran the command, the result is the same: no admin user.

The last lines in the logging are the start of transaction to create the contact & the insert but no commit.
[dev.log](https://github.com/sulu/sulu/files/7574857/dev.log)

**Comment by marcelkussin** [comment] 2021-11-21 13:04
Same here. i just used the sulu docker and i get the smae dev.log like @kwinne but in the console "bin/adminconsole sulu:build dev" it outputs an "Segmentation fault".

`bin/adminconsole sulu:build dev
Build Targets
=============

+---+--------------------+---------------------------------------------------------------------------------+
| # | Builder            | Deps                                                                            |
+---+--------------------+---------------------------------------------------------------------------------+
| 0 | database           |                                                                                 |
| 1 | phpcr              | database                                                                        |
| 2 | phpcr_migrations   | phpcr                                                                           |
| 3 | fixtures           | database, phpcr                                                                 |
| 4 | user               | fixtures, database                                                              |
| 5 | system_collections | database, fixtures                                                              |
| 6 | security           | fixtures, database                                                              |
| 7 | dev                | database, fixtures, phpcr, user, phpcr_migrations, system_collections, security |
+---+--------------------+---------------------------------------------------------------------------------+

Options:

  - nodeps: false
  - keep-exit-code: false
  - destroy: false
  - help: false
  - quiet: false
  - verbose: false
  - version: false
  - ansi: false
  - no-interaction: false
  - env: 'dev'
  - no-debug: false

Look good? (y)

Executing builders
==================

Target: database

    doctrine:schema:update  ({"--force":true})
    
        
                                                                                                                                        
         [OK] Nothing to update - your database is already in sync with the current entity metadata.                            
                                                                                                                                
        
                
Target: phpcr

    sulu:document:initialize
    
        sulu_document_manager.initializer.workspace
          [ ] workspace: "default"
          [ ] workspace: "default_live"
        sulu_document_manager.initializer.root_path_purge_initializer
          [ ] Purging workspaces
        sulu_page.document_manager.content_initializer
          content namespaces:
          [ ] sulu:http://sulu.io/phpcr
          [ ] sec:http://sulu.io/phpcr/sec
          [ ] settings:http://sulu.io/phpcr/settings
          [ ] i18n:http://sulu.io/phpcr/locale
          content node types:
          [*] sulu:base
          [*] sulu:path
          [*] sulu:content
          [*] sulu:snippet
          [*] sulu:page
          [*] sulu:home
          content namespaces:
          [ ] sulu:http://sulu.io/phpcr
          [ ] sec:http://sulu.io/phpcr/sec
          [ ] settings:http://sulu.io/phpcr/settings
          [ ] i18n:http://sulu.io/phpcr/locale
          content node types:
          [*] sulu:base
          [*] sulu:path
          [*] sulu:content
          [*] sulu:snippet
          [*] sulu:page
          [*] sulu:home
        sulu_core.webspace.document_manager.webspace_initializer
          [ ] homepage: /cmf/example/contents (en)
          [ ] route: /cmf/example/routes/en (en)
        sulu_snippet.document.snippet_initializer
          [ ] snippet path:: /cmf/snippets 
          [ ] snippet path:: /cmf/snippets 
        sulu_custom_urls.initializer
          example.com:
          [ ] items path:: /cmf/example/custom-urls/items 
          [ ] items path:: /cmf/example/custom-urls/routes 
        
                * Legend: [+] Added [*] Updated [-] Purged [ ] No change
        
Target: phpcr_migrations

Target: fixtures

    doctrine:fixtures:load  ({"--no-interaction":true,"--append":true})
    
        
                   > loading App\DataFixtures\AppFixtures
           > loading [2] Sulu\Bundle\ContactBundle\DataFixtures\ORM\LoadDefaultTypes
           > loading [3] Sulu\Bundle\MediaBundle\DataFixtures\ORM\LoadCollectionTypes
           > loading [4] Sulu\Bundle\MediaBundle\DataFixtures\ORM\LoadMediaTypes
           > loading [5] Sulu\Bundle\SecurityBundle\DataFixtures\ORM\LoadSecurityTypes
        
    sulu:document:fixtures:load  ({"--no-interaction":true,"--append":true})
    
        Could not find any fixtures.
        
Target: user

    sulu:security:role:create  ({"name":"User","system":"Sulu"})
    
        Role "User" already exists.
        
        Created role "User" in system "Sulu"
    sulu:security:user:create  ({"username":"admin","firstName":"Adam","lastName":"Ministrator","email":"admin@example.com","locale":"en","role":"User","password":"admin"})`

note: thats the second attempt calling the command, the database is created and added correctly

**Comment by alexander-schranz** [comment] 2021-11-21 13:12
> Segmentation fault".

If you currently running into a segmentation fault it is caused by a new release of the `jms/metadata` package add the following to your comoser.json to add a conflict:

```
    "conflict": {
        "jms/metadata": "2.5.2",
    }
```

And run then `composer update`. The version is already conflicted in the latest dev branches and so in the next releases: https://github.com/sulu/sulu/pull/6365/files

**Comment by kwinne** [comment] 2021-11-21 13:54
@alexander-schranz @marcelkussin 

I just tested adding the conflict and I can confirm, this has fixed the issue. 
The `bin/adminconsole sulu:build dev` now finishes successfully and the default admin user has been added.

Thanks for the help.

**Comment by marcelkussin** [comment] 2021-11-21 14:11
i can confirm too, this fixes the issue

**Comment by alexander-schranz** [comment] 2021-11-21 14:38
Thank you for the feedback!

**Comment by alexander-schranz** [comment] 2021-11-21 21:30
Compatibility fixed by a new massive search bundle version: https://github.com/massiveart/MassiveSearchBundle/releases/tag/2.6.3. Run `composer update` to get the latest compatible version.

Thank you for reporting!

**Closed as completed by alexander-schranz** 2021-11-21 21:30 UTC
