### ISSUE TITLE
Handling login in both admin and website parts

### ISSUE THREAD

**Issue by sarramegnag** [sulu/sulu#3498] opened 2017-08-24 09:58 UTC
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.4.10
| Browser Version | All

#### Actual Behavior

When I log in the admin, I'm not logged in the website.

#### Expected Behavior

I would like both parts share the same context.

#### Steps to Reproduce

Log in the admin, switch to website and check you're not logged in.

#### Possible Solutions

I tried playing with `context` key in firewalls but it doesn't work. Mainly because I think that website is not aware of admin security and vice versa.

For info, I'm using https://github.com/sulu/SuluCommunityBundle/ too.

https://stackoverflow.com/questions/31288004/symfony-impersonation-separate-firewalls-and-separate-user-providers
https://stackoverflow.com/questions/11801622/how-to-authenticate-on-2-different-symfony2-firewalls-at-the-same-time

**Comment by wachterjohannes** [comment] 2017-08-24 12:16
the problem is not that you have to authenticate between two firewalls. in sulu we have to completely divided applications (website and admin). but maybe we found a way to achieve that.

**Comment by SarramegnaG** [comment] 2017-08-24 12:29
Ok, I'm waiting to know if you have way to achieve that.

**Comment by danrot** [comment] 2019-11-27 07:57
We've actually built it like this on purpose, because the user you have been logged in with in the admin might not have any permissions on the website. Therefore going to close this issue.

**Closed by danrot** 2019-11-27 07:57 UTC
