### ISSUE TITLE
Image in portrait mode are turned

### ISSUE THREAD

**Issue by rogoit** [sulu/sulu#6159] opened 2021-07-24 13:57 UTC
| Q | A
| --- | ---
| Sulu Version | 2.3.1
| PHP Version | 7.4

# Actual Behavior
When I upload a image in portrait modus it is turned

# Expected Behavior
Get the image like uploaded

# Steps to Reproduce
Try images from here
![Bildschirmfoto vom 2021-07-24 15-53-48](https://user-images.githubusercontent.com/3101439/126870658-3309fd87-4b19-4946-9df9-6aef7fd47c02.png)
![20210718_204745](https://user-images.githubusercontent.com/3101439/126870673-8ba4cf7e-2d4a-4558-bbb2-6a1d0a81587e.jpg)

**Comment by alexander-schranz** [comment] 2021-07-25 13:57
Most cameras save images only in landscape mode and only use a exif meta header to set the image rotation.

The rotation of an image is detected by the Imagine Library. It uses the standard exif orientation headers of an image for it. The method doing this can be found here: https://github.com/avalanche123/Imagine/blob/b6b631517a5c50ebfad0e0576ef9aeb9fd10d1dc/src/Filter/Basic/Autorotate.php#L86.
It requires that you have the `exif` php extension is installed so such headers can be read, so maybe this is the cause in your case that the rotation is not correctly detected as maybe exif is not installed on your machine.

**Comment by rogoit** [comment] 2021-07-25 19:19
I will try next days thx

**Comment by niklasnatter** [comment] 2021-08-03 08:13
As mentioned by @alexander-schranz, this should already work if the `exif` php extension is installed on the server. The functionality was implemented in #4236. Because of this, I am closing this issue. 

Please feel free to open a new issue if the problem persists after enabling the `exif` extension 🙂

**Closed as completed by niklasnatter** 2021-08-03 08:13 UTC
Labels: Bug
