### ISSUE TITLE
Single internal link pointing to an external link not being published with a URL does not work

### ISSUE THREAD

**Issue by aureliusm** [sulu/sulu#4979] opened 2020-01-15 11:35 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.29
| Browser Version | Any browser - not related

#### Actual Behavior

We have created a new external link on a sub-locale (/fr). The main locale is (/en). Then on an other page we created a `single_internal_link` that points to that external link. However, the redirect to external link does not happen when I click the internal link button `<sulu:link href="{{ block.button_link }}" [...]` . Even if I type the external url directly in a browser `our-domain.com/fr/sample-external-link` it also doesn’t work - gives a 404 page instead of redirecting.

**Important**: If I do the same on the base locale so the url is e.g. `domain.com/sample-external-link` that works just fine -> it redirects.

#### Expected Behavior

If I create an external_link page in **any** locale, if I link to that page via a single_internal_link or go directly to the external_link page (e.g. `our-domain.com/fr/sample-external-link`), I should be redirected to the external url.

#### Possible Solutions

As it works with the default locale, there has to be something going on with the sub-locale parsing in the url.

@alexander-schranz suggested on slack: "It looks like the PageLinkProvider services doesn’t handle Internal or External Links correctly".

**Comment by danrot** [comment] 2020-01-15 14:59
I somehow can't reproduce this issue... Can you maybe deliver more steps to reproduce? Maybe even paste your webspace and template configuration? What I've tried so far is the following:

1. Create a page in the "de" locale
2. Make this page an external link to www.google.at
3. If I now visit this page I am correctly redirect to www.google.at

I've also checked a single internal link content type in a different template with the `<sulu:link href="{{content.single_internal_link}}">Test</sulu:link>` tag, which also worked correctly. (The only thing not working was including the port, but that is a different issue)

**Comment by danrot** [comment] 2020-01-15 15:25
@aureliusm We have played around a bit, and found out that what you have written here is not really relevant to the problem. Is it possible that this only occurs if you follow these steps:

1. Create a page in any locale, and save it only as a draft
2. Switch to the settings tab, click external link and enter a URL
3. Save and publish the page

Only if you have saved the page as draft in the first step, we can reproduce the problem that the URL of the page does not redirect.

This can be solved in two ways IMO, whereby we can also apply both fixes:

1. The `<sulu:link/>` tag must already render the correct URL instead of relying on the redirect to happen
2. When publishing a page, that has not been published before, on the settings tab, we should also create that URL (it looks to me like that is what you've expected to happen)

**Comment by aureliusm** [comment] 2020-01-16 07:36
@danrot Thank you for a quick response! Yes, I can confirm! I must have used SAVE AS DRAFT when doing it on a non-default locale and SAVE AND PUBLISH on the default domain and that lead to the wrong conclusion. 

Regarding proposed solutions, I really like number 1, because this is what we basically want as the end-result -> to go to that final external url and it makes sense also from SEO perspective to prevent unnecessary internal redirects.

As for fix no. 2 - I think that if you are able to select the "draft external link page" in the internal_link selector, it should work in the end - that is what basically confused us.

**Comment by niklasnatter** [comment] 2021-10-06 12:58
Thanks a lot for reporting! This should be fixed in #6263

**Closed by niklasnatter** 2021-10-06 12:58 UTC
Labels: Bug
