### ISSUE TITLE
Handle deleted contact in contact selection

### ISSUE THREAD

**Issue by rs2487** [sulu/sulu#6512] opened 2022-03-23 12:15 UTC
| Q | A
| --- | ---
| Sulu Version | 2.3.1
| PHP Version | 7.4
| DB Version | 5.7
| Browser Version | FF

# Actual Behavior

Contact selection crahes when open it in Admin, if the before selected contact was deleted in the meantime.
End in an endless loop which tries to load the deleted contact.

# Expected Behavior

Contact selection should not try to display the deleted contact. On saving the id of the deleted contact should no longer persited.

# Steps to Reproduce

- Open a page with a contact selection in Sulu Admin
- Add a contct in the selection
- Go to the Contacts area in Sulu and delete the before selected contact.
- Open the page again.

**Comment by luca-rath** [comment] 2022-03-23 14:24
I cannot reproduce this problem using Sulu 2.4.0 with the `contact_selection` nor with the `single_contact_selection` ... After deleting the contact, the response of the page still contains the deleted contact's id (e.g. `2`), then a request to `/admin/api/contacts/2` is made which results in a `404`, but there is no infinite loop. I can still open the contact selection, select a different contact and save the page

**Comment by rs2487** [comment] 2022-03-23 14:54
So do you think the bug is eliminated with an Update to Sulu 2.4.0?

**Comment by luca-rath** [comment] 2022-03-24 09:42
I cannot reproduce that bug with Sulu 2.3.1 either ... you are using a `contact_selection` property, right?

**Comment by rs2487** [comment] 2022-03-25 06:32
It is a `contact_account_selection`, sorry. Did not know that there are two different types.
I can reproduce it on another Sulu installation with Version `2.3.7`.

**Comment by luca-rath** [comment] 2022-03-25 09:03
Seems to be related to this line: https://github.com/sulu/sulu/blob/2.x/src/Sulu/Bundle/ContactBundle/Resources/js/containers/ContactAccountSelection/ContactAccountSelection.js#L47

**Comment by luca-rath** [comment] 2022-04-05 12:04
Fixed by #6519

**Closed as completed by luca-rath** 2022-04-05 12:04 UTC
Labels: Bug
