### ISSUE TITLE
Media item > History | Previous versions not found error 

### ISSUE THREAD

**Issue by tapasa30** [sulu/sulu#7480] opened 2024-06-25 13:26 UTC
| Q | A
| --- | ---
| Sulu Version | 2.5.18 (Also 2.6)
| PHP Version | 8.2
| DB Version | MySQL 8.0
| Browser Version | Edge/Chrome...

# Actual Behavior

Changing the file in the media menu creates a new version of the file that you can see in the History tab. The issue arises when you want to view a previous version by clicking on the eye icon.
It throws a **not found** exception.

# Expected Behavior

The same as clicking the current version. Show the selected file, in this case, a previous version of the Media item.

# Steps to Reproduce

Optional: Create a new media file from the Admin menu **Media**.
Do what is indicated in **Actual Behavior**, that is, modify the media by **Uploading a new version**, then try to view any previous version.

# Possible Solutions

I see here that `MediaRepository::findMediaByIdForRendering` is only retrieving one version. This is called from the download action in `MediaStreamController`, inside the `getFileVersion` method.

`->leftJoin('file.fileVersions', 'fileVersion', Join::WITH, 'file.version = fileVersion.version')`

I just removed `Join::WITH, 'file.version = fileVersion.version` and everything is working fine.

I am not sure if I should upload a fix because I do not have much context on Sulu/Media core, so I will leave this here for someone else to make that decision.

**Comment by tapasa30** [comment] 2024-06-25 13:29
I see is fixed here https://github.com/sulu/sulu/issues/7319

**Comment by tapasa30** [comment] 2024-06-25 13:36
I thought this was fixed here https://github.com/sulu/sulu/issues/7319 but I just tested Sulu 2.6 and still throwing the error

**Comment by alexander-schranz** [comment] 2024-06-25 14:00
Thx for report I will close this as duplicate of #7480 please add your information to the #7480 issue. If you want to give a try for a fix I think `findMediaByIdForRendering` should get the version as a parameter if possible.

**Closed as completed** 2024-06-27 11:04 UTC
Labels: Bug
