### ISSUE TITLE
Changing URL in parent Page is not updating url in child pages

### ISSUE THREAD

**Issue by davidhoelzel** [sulu/sulu#6004] opened 2021-05-06 14:04 UTC
| Q | A
| --- | ---
| Sulu Version | 2.2.7
| PHP Version | 8.0.3
| DB Version | Postgres 12.2
| Browser Version | Does not matter

# Actual Behavior

When the url of a parent page is changed, the child pages are not updated accordingly, at least in website phpcr workspace.
As consequence, all sulu_navigation_* methods return for child pages the outdated urls.
Openening these urls results in a (correct) 301 redirect to the actual url.
It seems that the document is updated correctly in admin phpcr workspace but not in website phpcr workspace. Therefore, in admin preview, the links are generated correctly, but remain outdated in website context.

# Expected Behavior

Admin and Website workspace contain the same data for documents after publishing.

# Steps to Reproduce

Create a page with url "/url"
Create a sub-page with url "/url/subpage"
Publish both pages.
Change address of sub-page to "/url/subpage-changed"
Publish
Change address of the parent page to "/url-changed"
Publish
Reload admin preview -> links for sub-page are pointing correctly to "/url-changed/subpage"
Open/Reload webpage -> all links of the subpage are still pointing to "/url/subpage-changed" -> openening these -> 301 redirect to "/url-changed/subpage-changed"

You just need to open the nodes (for the sub-page) in the respective workspace in phpcr shell and see that different urls are saved:
Admin workspace:
url: /url-changed/subpage-changed

Website workspace:
url: /url/subpage-changed

# Possible Solutions

The only solution is to re-publish all child pages individually, either by setting a new url or changing the content to publish it again.
Manually updating the phpcr data should not be an option:-)

**Comment by alexander-schranz** [comment] 2021-05-06 14:11
@davidhoelzel Thank you for creating this issue. There is an exist issue for the same Problem here #4990 so I will close this one to avoid duplication. If you want to add additional information please feel free there. Currently the problem is that we would need to implement something like `partial` publishing of the child pages so only that the new `url` is published for them and not that accidentally unknown draft data is published.

**Closed as completed by alexander-schranz** 2021-05-06 14:11 UTC
Labels: Bug
