### ISSUE TITLE
Back in snippets not possible

### ISSUE THREAD

**Issue by mmsbrggr** [sulu/sulu#2574] opened 2016-07-11 13:24 UTC
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.1 |
| Browser Version | all |
#### Actual Behavior

When navigate to the snippets section and pressing the browser's back button, the browser stays on the snippets overview.
#### Expected Behavior

When navigating to the snippets overview and pressing the browser's back button, the application should navigate back to the page the user was before.
#### Steps to Reproduce

Login -> Navigate to content tree -> Navigate to snippets -> Press history back button

**Comment by marcelmoosbrugger** [comment] 2016-07-12 05:44
This also happens in the content-tree, but only sometimes. I can't reproduce it regularly.

**Comment by alexander-schranz** [comment] 2016-10-12 13:39
seems to be also when you try to history back in category overview and category detail. seems like there in some places missing the locale and so it the route without a locale match and this will redirect.

**Comment by danrot** [comment] 2016-11-10 10:30
I am sure in the ContentBundle it is related to [this line](https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/ContentBundle/Resources/public/js/main.js#L151). It's probably something similar for the snippets. We should probably get rid of these redirects, or try to call the router with the `replace` option set to true. I think then it should not remove one of the routes from the history, and the back button should be working.

**Comment by danrot** [comment] 2019-11-07 07:49
This has been fixed in the mean time :slightly_smiling_face:

**Closed by danrot** 2019-11-07 07:49 UTC
Labels: Bug
