### ISSUE TITLE
ItemMetadata name don't convert to int/float

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#4320] opened 2018-12-13 09:34 UTC
| Q | A
| --- | ---
| Bug? | yes/no
| New Feature? | no
| Sulu Version | dev
| Browser Version | *

#### Actual Behavior

Currently we are converting the name of a property from the xml into `string|int|float`.
This is done because we are using `name` as value in the select.
But this feature could lead to big problems in php when float is used as array index.

#### Expected Behavior

In my opinion we shouldn't convert it and fix it in the select.

**Comment by trickreich** [comment] 2018-12-13 09:35
@sulu/core-team We should decided if we can fix this before the 2.0 release.

**Comment by danrot** [comment] 2018-12-17 14:58
The issue is a bit deeper than what you have described here. The thing is that the `name` on the param is a mandatory attribute, but the value isn't. I would say ideally we have something like the following:

```xml
<param value="4"/>
```

But since `name` cannot be omitted, we've decided to keep the old structure from Sulu 1.6:

```xml
<param name="4"/>
```

If we want to fix that properly we have to change that none of both attributes are not required.

Apart from that there is also another solution: We could use a plain array with numeric indices instead of using the name as the key.

**Comment by danrot** [comment] 2019-12-05 19:29
I don't think that we are going to touch this, unless it makes any problems (which it hasn't until now). Therefore going to close it.

**Closed by danrot** 2019-12-05 19:29 UTC
