### ISSUE TITLE
Add support for SQLite

### ISSUE THREAD

**Issue by webmozart** [sulu/sulu#2048] opened 2016-02-25 16:21 UTC
In order to simplify the installation of Sulu as much as possible, we should add support for SQLite. In a second step, SQLite should be the default database backend for Sulu Standard. The goal is that users are able to set up Sulu within minutes, even without reading the documentation.

At the moment, SQLite is not supported. There are more than a few issues to be resolved, the first one is that the build command does not work:

```
$ app/console sulu:build prod
...
Executing builders
==================

Target: database



      [Doctrine\DBAL\DBALException]                                                                                
      Operation 'Doctrine\DBAL\Platforms\AbstractPlatform::getListDatabasesSQL' is not supported by platform.  


    sulu:build [-D|--nodeps] [--destroy] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> [<target>]
```

The others are:

TODO:
- [ ] DBAL does not support foreign keys with the SqliteDriver (although they are technically supported by Sqlite) (see [Doctrine DBAL issue](https://github.com/doctrine/dbal/issues/999) for example). This means that cascade DELETE does not work, which will cause problems
- [ ] Sulu build fails because `listDatabases` method does not apply to an Sqlite database.
- [x] ~~Jackalope DBAL with Sqlite does not correctly compare multi-value numerical properties, see [Jackalope DBAL issue](https://github.com/jackalope/jackalope-doctrine-dbal/pull/327).~~ Supported as of Jackalope DBAL 1.2.7.

**Comment by danrot** [comment] 2016-02-25 19:21
For reference, there is already a similar issue: https://github.com/sulu-io/sulu/issues/2010

**Comment by danrot** [comment] 2016-02-29 10:23
[This line](https://github.com/sulu-io/sulu/blob/f4c53544716e1cb9c6903f17e40a2109d1231f76/src/Sulu/Bundle/CoreBundle/Build/DatabaseBuilder.php#L48) seems to be the problem. It is required to find out if the database already exists, so that the command can act accordingly. It seems that the listing of databases is not supported by SQLite.

**Comment by webmozart** [comment] 2016-02-29 15:49
@danrot Can we find a solution that does not require this line? E.g. explicitly create the database using a separate command?

**Comment by danrot** [comment] 2016-02-29 20:19
I have just tried to create the DB before running ` sulu:build`, removed this line, and it worked. With working I mean that at least a page could be saved :smiley: We should probably also try to enable tests for that on travis.

But maybe we don't even have to remove the line, an exception is thrown because of it, maybe we can catch it, and use a different mechanism to find out if the database exists?

**Comment by danrot** [comment] 2016-03-15 09:50
Another question here is how to solve that in the `parameters.yml` file. From what I have seen in the [doctrine documentation](http://doctrine-orm.readthedocs.org/projects/doctrine-dbal/en/latest/reference/configuration.html#pdo-sqlite) the configuration differs when using sqlite, e.g. we need a path here instead of a host. A solution would be to [connect via a URL](http://doctrine-orm.readthedocs.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url), but that's probably more difficult for beginners.

@webmozart @chirimoya @wachterjohannes @dantleech WDYT?

**Comment by dantleech** [comment] 2016-03-15 09:57
I think the parameters.yml should just have the dbal fields:

```
database:
    host: localhost
    path: /path/to/sqlite.db
    username: foo
    password: bar
    driver: pdo_sqlite
```

Then the user can look at the dbal documentation for a reference on how to configure this.

The current configuration lists both mysql and pgsql options, which gives the impression that both are used concurrently somehow...

**Comment by danrot** [comment] 2016-03-15 10:28
@dantleech What are you talking about? Our [parameters.yml.dist](https://github.com/sulu-io/sulu-standard/blob/develop/app/config/parameters.yml.dist) only shows options valid for both, mysql and pgsql. The problem is that sqlite would need a new `database_path` option or something similar.

**Comment by dantleech** [comment] 2016-03-15 11:01
Hmm. Mine didn't look like that. Anyway,

The symfony CMF standard looks as follows:


```
parameters:
    database_driver:   pdo_sqlite
    database_path: '%kernel.root_dir%/app.sqlite'
    database_host: null
    database_port: null
    database_name: null
    database_user: null
    database_password: null

    # ...
```

**Comment by danrot** [comment] 2016-03-15 14:02
And it just takes the values the current driver needs? Is that the way we should solve it?

**Comment by webmozart** [comment] 2016-03-25 12:46
@danrot Yes, I think so. :)

**Comment by dantleech** [comment] 2016-04-05 06:33
Updated the description with a list of things that need to be done in order for the tests to pass with sqlite.

**Comment by dantleech** [comment] 2016-04-05 06:35
The parameters.yml question is addressed here: https://github.com/sulu/sulu/pull/2210/files#diff-cd5dc3185849e36aa80b84d58514b2e5R4. This change should be adopted in sulu-standard.

**Comment by webmozart** [comment] 2016-05-10 12:56
The Jackalope issue is fixed in 1.2.7.

@danrot Can we get rid of the `listDatabases()` call?

**Comment by webmozart** [comment] 2016-05-10 13:05
Here's a PR that tries to fix the foreign key support of Doctrine's SQLite driver: https://github.com/doctrine/dbal/pull/821

**Comment by danrot** [comment] 2016-05-11 07:57
TBH, I don't really know any other way to determine if the database exists or not. But what I know is that we definitely need this information, otherwise the `--destroy` option can't drop the database. Maybe we can get our way around with some try/catch blocks instead of trying to find out beforehand. But I think I would need some time to investigate that in more detail, and it might probably not worth it before we get SQLite running in general (talking about the foreign key support in particular).

**Comment by dantleech** [comment] 2016-05-11 08:24
You can always create a custom Dbal\Connection class with a `databaseExists`
method. Then you could (if required) intercept the connection parameters
to determine the `path` of the sqlite database.

**Comment by danrot** [comment] 2017-02-22 15:19
I am closing this, since Doctrine ORM doesn't support foreign keys with SQLite.

**Closed by danrot** 2017-02-22 15:19 UTC
Labels: Bug, DX, Enhancement

**Comment by dantleech** [comment] 2017-02-22 15:38
Rather DBAL doesn't and arguably should?

On 22 February 2017 15:19:26 GMT+00:00, Daniel Rotter <notifications@github.com> wrote:
>I am closing this, since Doctrine ORM doesn't support foreign keys with
>SQLite.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sulu/sulu/issues/2048#issuecomment-281699301

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by danrot** [comment] 2017-02-23 07:37
Maybe it should, but it is an upstream issue we can't put in too much energy now...
