### ISSUE TITLE
Template changes not visible

### ISSUE THREAD

**Issue by Clindbergh** [sulu/sulu#5423] opened 2020-07-21 10:10 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.1
| Browser Version | Firefox and Edge tested

#### Actual Behavior

When changing a template in production mode the changes are not applied in the frontend.

#### Expected Behavior

The changes to be applied.

#### Steps to Reproduce

1. Setup a new instance in production mode
2. Edit the homepage and add a subpage using the default template and publish both.
3. Edit the base template (e.g. remove the search bar) and add something to the subpage.
4. (Optional) Clear and warmup the cache using `php bin/adminconsole cache:clear` and `php bin/adminconsole cache:warmup`
5. (Optional) Hard refresh your browser (Firefox: CTRL + F5 or CTRL + SHIFT + R) or open up the page in another browser

#### Possible Solutions

`rm -rf var/cache/*` will make the change appear, but isn't that the point of the console command?

**Comment by Clindbergh** [comment] 2020-07-21 16:23
> Do you use the default http cache or a varnish?

default cache

> In which environment do you have this problems?

prod

>  Do you have any error if you click `Save & Publish` in the log files?

No errors in the log files.

> Can you reproduce this error in the default sulu skeleton or does it only appear in your project?

I did reproduce it in a separate instance using the default skeleton. 

**Note** : If I edit a page, *after* the template change, it appears to work as expected. However, it's impractical to edit, change content and republish each page that uses the template.

> For changes in the xml a hard cache remove is needed.

If a hard cache (meaning `rm -rf var/cache/*`) is indeed the only way to apply edits to existing page configuration (and maybe templates as well), then this should definitely be mentioned somewhere in the docs. I have only discovered this coincidentally and it's counter-intuitive that `bin/<any-of-the-consoles> cache:clear` is not sufficient.

**Comment by alexander-schranz** [comment] 2020-07-21 16:35
> Note : If I edit a page, after the template change

So to make sure are you talking about changing **content** so things like a text over the admin UI or are you talking about changing the **xml or twig** files?

Over the Admin UI republish should show the changes else please its maybe a bug with phpcr cache or http cache, maybe you could try to disable the phpcr cache by comment [this](https://github.com/sulu/skeleton/blob/2.1.0/config/packages/prod/sulu_document_manager.yaml) configuration.

If you edit xml and twig files the fastest way to clear the twig and structure caches is doing `rm -rf var/cache/`, but also `bin/adminconsole cache:clear && bin/websiteconsole cache:clear` should clear the caches and twig and structure cache should not be longer fresh. Maybe you can debug it [this cache](https://github.com/sulu/sulu/blob/f9fac47e6d9c719921ef013d6c86478554beb65b/src/Sulu/Component/Content/Metadata/Factory/StructureMetadataFactory.php#L96).

**Comment by nnatter** [comment] 2020-07-22 07:57
Hey @Clindbergh,
can you provide an example repository where this happens or the exact steps how to reproduce this with the `sulu/skeleton`?

**Comment by Clindbergh** [comment] 2020-07-22 08:53
> So to make sure are you talking about changing content so things like a text over the admin UI or are you talking about changing the xml or twig files?

I was talking about twig. 

> exact steps how to reproduce this with the sulu/skeleton

Here are exact steps to reproduce:

* `composer create-project sulu/skeleton my-project -n`
* `cd my-project`
* Add the db string to  `.env`
* `rm .env.local` (so we're not in the dev env)
* `php bin/adminconsole sulu:build prod` 
* Create the admin role and user
   * `php bin/adminconsole sulu:security:role:create`
   * `php bin/adminconsole sulu:security:user:create`
* Visit the page in the browser
* `vim templates/base.html.twig` (e.g. remove the search form)
* Visit the page in the browser

**Result:** The search bar is still visible in the browser.

**Next step**:

* `bin/adminconsole cache:clear && bin/websiteconsole cache:clear`
* Visit the page in the browser

**Result:** The search bar is still visible in the browser.

**Next step**:

* ` rm -rf var/cache/*`
* Visit the page in the browser

**Result:** Now the search bar is removed on the homepage.

**Summary:** A hard cache (`rm`) remove is required to have template (twig) changes applied, but this behaviour is not documented.

**Comment by alexander-schranz** [comment] 2020-07-22 09:15
@Clindbergh If you run `cache:clear` commands it will currently not remove the `http_cache` folder in sulu or clear the varnish servers. Not sure if there are any commands to clear the whole http cache from CLI. /cc @dbu

**Comment by dbu** [comment] 2020-07-22 09:27
you can run `fos:httpcache:invalidate:regex ".*"` to invalidate the http cache. 

when using the symfony http cache, i could see the point that cache:clear could clear the web cache as well. with varnish, this would feel weird however. but doing it for one but not the other is also odd. i don't think we want to do it.

if sulu offers editing templates on the live system, it should imho tag responses with the templates (or hashes of them) and offer to invalidate the cache by tag when a template is edited. (on a large installation, you probably don't want this to automatically happen. could be a configuration option whether to do it automatically, and there could be some control button in the template editor after saving the template or something)

**Comment by alexander-schranz** [comment] 2020-07-22 09:38
@dbu seems like `fos:httpcache:invalidate:regex ".*"` does not work for the symfony cache (errors with: `HTTP cache does not support BAN requests`). The cache:clear command does in our case not work because the `http_cache` directory is stored in `var/cache/common) and so not inside the symfony container cache because of our 2 Kernel setup else invalidating from admin would not work.

Maybe a `fos_httpcache:invalidate:domain` could be introduced which calls [invalidateDomain](https://github.com/sulu/sulu/blob/89518be214a030c68d12c16a459f2ef74beced4d/src/Sulu/Bundle/WebsiteBundle/Cache/CacheClearer.php#L80) so a specific domain can be cleared in deployment which would work also for varnish and symfony http cache.

**Comment by alexander-schranz** [comment] 2020-07-22 10:04
@dbu Sorry I misinterpreted the code. The `invalidateDomain` function is only called for varnish and we are clearing the folder ourselves 🙈 . What do you think to add a new command which will clear to the whole varnish over ban and in case of the http cache clear that directory. E.g.: `bin/console fos:httpcache:invalidate:all`

**Comment by dbu** [comment] 2020-07-22 10:07
we have a ClearCapable interface in FOSHttpCache which can clear the whole symfony http cache directory. it would make sense to expose that with a command - i'd call it `fos:httpcache:clear`. we could make the command check for ClearCapable and then fall back to check if we talk to varnish and if so call `ban('.*')`

**Comment by alexander-schranz** [comment] 2020-07-22 11:52
I will close this issue in favor of https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/544

**Closed by alexander-schranz** 2020-07-22 11:52 UTC
