### ISSUE TITLE
Published pages broken in certain locale in production

### ISSUE THREAD

**Issue by davidhoelzel** [sulu/sulu#5970] opened 2021-04-28 14:16 UTC
Hello,
we are encoutering a strange behaviour:
publishing pages in one of our localizations works, but data in phpcr is not updated (only in website workspace). This worked flawlessly for the last couple of months. 
Unfortunately, we are not able to reproduce this behaviour in dev, no matter how hard we try.

Setup:
Affected Locale: en_us
sulu version: 2.2.5

Here is the setup for that webspace:

```xml
<?xml version="1.0" encoding="utf-8"?>
<webspace xmlns="http://schemas.sulu.io/webspace/webspace"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/webspace/webspace http://schemas.sulu.io/webspace/webspace-1.1.xsd">

    <name>Webspace Name</name>
    <key>webspacekey</key>

    <localizations>
        <localization language="de" default="true"/>
        <localization language="en"/>
        <localization language="en" country="us"/>
    </localizations>
<navigation>
        <contexts>
            <context key="main">
                <meta>
                    <title lang="en">Main Navigation</title>
                    <title lang="de">Hauptnavigation</title>
                </meta>
            </context>
            <context key="footer" >
                <meta>
                    <title lang="en">Footer</title>
                    <title lang="de">Footer</title>
                </meta>
            </context>
        </contexts>
    </navigation>

    <portals>
        <portal>
            <name>Portal Name</name>
            <key>webspacekey</key>
            <environments>
                <environment type="prod">
                    <urls>
                        <url>www.prod.domain/{localization}</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
</webspace>
```

When we publish a page for locale "de" or "en", the content-repository in admin and webspace  workspaces looks fine. For both locales, we can see the corresponding data in the phpcr shell, e.g.
i18n:de-author                         | STRING (2)     | 45                                                  | 
i18n:de-authored                     | DATE (29)       | 2021-04-06T10:28:35+02:00        |
...
i18n:en-author                         | STRING (2)      | 54                                                 |
...

Also for already published pages in en_us, the data looks fine:
i18n:en_us-author                    | STRING (2)      | 53                                                 | 
...

When we now add a new page in en_us, we can edit normally. 
When we publish the page, the admin UI says OK, in admin phpcr workspace the data seems to be correctly updated.
But in website workspace nothing is added for the locale en_us.
There is no error in the logs.

As a result, when we call sulu_navigation_root_tree in our template in that locale, there is no data for that page, the only data contained is children. Which contains only the already published pages. It does not matter where in the navigation tree the page is located, the data for these newly published pages is always completely empty for that locale.
The array structure returned by sulu_navigation_root_tree looks like this:
```php
Array
                (
                    [children] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 65caa90d-cfd1-4df8-a536-84462808ac45
                                    [uuid] => 65caa90d-cfd1-4df8-a536-84462808ac45
                                    [nodeType] => 1
                                    [path] => /anforderungen/online-buchung
                                    [changed] => Array
                                        (
                                            [date] => 2021-04-16 15:35:45.538000
                                            [timezone_type] => 1
                                            [timezone] => +02:00
                                        )

                                    [changer] => 19
                                    [created] => Array
                                        (
                                            [date] => 2021-04-08 09:11:57.066000
                                            [timezone_type] => 1
                                            [timezone] => +02:00
                                        )

                                    [publishedState] => 1
                                    [published] => Array
                                        (
                                            [date] => 2021-04-08 09:12:31.880000
                                            [timezone_type] => 1
                                            [timezone] => +02:00
                                        )

                                    [creator] => 28
                                    [title] => Online Booking
                                    [locale] => en_us
...
```

We already tried to copy the content from the "en" locale and re-publish, but to no avail.

Any ideas?

Thank you!

**Comment by alexander-schranz** [comment] 2021-04-28 15:02
Hello @davidhoelzel,

Does it happen only on this installation and this db? Do this error only happens on `prod` or also on `dev` environment with the same db dump? Can you reproduce it locally on `prod` env? Did you maybe add the localizations without running the document init command. See adding localization docs: https://docs.sulu.io/en/2.2/book/localization.html

**Comment by niklasnatter** [comment] 2021-04-28 15:50
Hey,
thanks for the detailed description! 
Does this happen for all pages or only for specific pages?

**Comment by davidhoelzel** [comment] 2021-04-29 06:06
Happens now for all pages as soon as we add it to any navigation context in that locale (new pages and already existing ones).
Only pages that were already published before that problem occurred are still working in navigation.
When not adding them to navigation context, the published pages are working as expected, but are therefore not available in navigation.

I will try to export the prod data and restore it in my dev environment.

**Comment by alexander-schranz** [comment] 2021-04-29 08:42
The structure you posted happens when a child page is part of the navigation but the parent page not. Does the page itself occur on the website or the url in the sitemap? How does the phpcr node look like you can with `bin/websiteconsole doctrine:phpcr:shell` then with:

```bash
cd <uuid>
ls
```

which should then output the whole node which should also shown the navigation contexts.

**Comment by davidhoelzel** [comment] 2021-04-29 08:53
Ah, I did not know that I have to exit the shell to see updated data:-)

Seems like the data for the node is correctly updated and even for locale en_us, the navigation context is set correctly:
| i18n:en_us-navContexts                 | STRING (4)      | [0] main
| i18n:en_us-published                   | DATE (29)       | 2021-04-29T10:47:57+02:00

But sulu_navigation_root_tree still returns only the child pages for that node.

**Comment by niklasnatter** [comment] 2021-04-29 09:00
@davidhoelzel You can use `refresh` inside of the shell to refresh the data of your session 🙂 

Does this mean that the data is updated correctly and only missing when using the `sulu_navigation_root_tree` function?

Does the same problem occur when using the `sulu_navigation_root_flat`, `sulu_navigation_tree` and `sulu_breadcrumb` function? 
Is it possible that there is some kind of navigation cache (#4084) implemented in your project?

**Comment by davidhoelzel** [comment] 2021-04-29 10:03
I must admit it is wrong that the sulu_navigation_root_tree method is called, it is rather NavigationMapper::getRootNavigation (with same arguments as sulu_navigation_root_tree calls that method). From the service @sulu_website.navigation_mapper.

Yes, we have implemented a navigation cache, but this only stores the data that is returned by navigationMapper->getRootNavigation and enriches some additional data needed by us. 

We are using the standard symfony cache and clear that cache on every publish/unpublish/reorder/move/remove/cacheClear event. 
The first pageView then builds that cache from start by calling NavigationMapper->getRootNavigation. But the method then only returns the children for affected pages and affected child pages.

The cache key depends on webspace, locale, depth and navigationContext. 

For all other webspaces and locales, even other locales in that webspace, this works. It even worked for that locale until the beginning of this week.

Our method looks like this:
```php
public function getRootNavigationItems(?string $context, int $depth, string $webSpaceKey, string $locale): array
    {
        $segment = $this->requestAnalyzer->getSegment();
        
        ### $data only contains 'children' when called with context 'main'
        $data = $this->navigationMapper->getRootNavigation(
            $webSpaceKey,
            $locale,
            $depth,
            false,
            $context,
            false,
            $segment ? $segment->getKey() : null
        );
        ...
}
```
We call that method with arguments:
- context: 'main'
- depth: 3
- webspaceKey: corresponding webspaceKey
- locale 'en_us'

**Comment by alexander-schranz** [comment] 2021-04-29 10:16
@davidhoelzel do you have the same issues when you disable the cache and also disable all other caches (normally they are disabled when you run it locally in your `dev`). For me it looks like a caching issue, would be nice if you try to debug it from which cache maybe something is loaded incorrectly.

**Comment by niklasnatter** [comment] 2021-04-29 10:47
From that description, I would suspect an issue in your custom cache. The answers to the following questions from above would still be interesting:

- Does this mean that the data is updated correctly and only missing when using the `sulu_navigation_root_tree` function? Do you see the updated data when visiting the page and in the PHPCR shell?
- Does the same problem occur when using the `sulu_navigation_root_flat`, `sulu_navigation_tree` and `sulu_breadcrumb` function?

**Comment by davidhoelzel** [comment] 2021-04-29 14:45
This has nothing todo with caching, I think this is is a bug in our code that does not handle the case of un-published pages.

As I understand that ListToTreeConverter that builds the navigation tree structure, it´s purpose is the following:
- go through found nodes
- if there are children contained but the node itself is not published -> add only the child pages, so the un-published node itself is not part of the navigation structure. This makes perfectly sense.

When we have a structure of pages like this

HomePage - Published
    SubPage - Not Published
        SubSubPage - Published

The navigation structure returned by sulu_navigation_root_tree looks like this:
```php
Array
                (
                    [children] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 65caa90d-cfd1-4df8-a536-84462808ac45
                                    [uuid] => 65caa90d-cfd1-4df8-a536-84462808ac45
                                    [nodeType] => 1
                                    [path] => /subPage/subSubPage
                                    ...
                         )
                  )
```

So I think this is a flaw in our menu-rendering that simply assumes that we always have the data available of the page where the children are contained.

Feel free to close  the issue if you agree that this is intended behaviour to return in navigation only data of published pages.

**Comment by niklasnatter** [comment] 2021-04-30 07:36
Thanks for the update! I will close this, feel free to create a new issue if you encounter any other problems 🙂

**Closed as completed by niklasnatter** 2021-04-30 07:36 UTC
Labels: Needs Information

**Comment by davidhoelzel** [comment] 2021-04-30 08:16
Just a sidenote: the method NavigationMapper::getNavigation returns a different structure and **does not return** published children for unpublished pages. This might be regarded as inconsistent and should therefore be made clear either in a code comment or the documentation.
