### ISSUE TITLE
url with sub dir defined in webspace adds sub dir again at the end of path after redirect

### ISSUE THREAD

**Issue by piratadelfuturo** [sulu/sulu#2542] opened 2016-07-06 05:33 UTC
| Q | A
| --- | ---
| Bug? | maybe
| New Feature? | no

#### Actual Behavior

I added in the webspace xml:  `<url>www.website.com/corp/{localization}</url>`

Then I type in the browser: www.website.com/corp
It redirects to: www.website.com/corp/en/corp

I tried setting the localization before the sub dir like:   `<url>www.website.com/{localization}/corp</url>`
But the result us the same: www.website.com/en/corp/corp

#### Expected Behavior

Maybe It should redirect same as if I was doing it directly under the domain only.

**Comment by danrot** [comment] 2016-07-15 11:13
Duplicate of #1068, and will be fixed with #2486

**Closed by danrot** 2016-07-15 11:13 UTC
