### ISSUE TITLE
Block won't show the currently selected type if only one type exists

### ISSUE THREAD

**Issue by kfrohwein** [sulu/sulu#5079] opened 2020-02-24 09:58 UTC
# Problem description
A sulu block currently won't show it's block type. So I have no clue what I am currently editing.

![block-slide](https://user-images.githubusercontent.com/245385/75142384-41405c00-56f3-11ea-8eb7-7a4aeb716f75.png)

If you have a single block type like in my example which is a slide for a swiper you could miss the information about what you are editing. If there are multiple block types you can see what currently is selected.

# Proposed solution
Currently I see 3 possible

1. Add the value of type -> meta -> title to the form as head line which is already used for the select box. So there is duplication but very verbose information.
2. Change or hide the select box widget so the current selection is more like a headline and if you click on it the choices appear. This is more a UX tweak and it should still be active if there is just one option.
3. Add another optional value to the XML for a "Block Type Headline" that is displayed if available. So might be an over configuration but keeps everything like it is. Maybe this already can be done by using a simple sulu information text XML.

**Comment by danrot** [comment] 2020-03-23 07:40
I think it was [implemented like this on purpose](https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/Block.js#L75)... Although I see that the way it is currently implemented is makes Block also lose some information, i.e. if the block component (in general, not only in the form) makes use of types at all, or if it does not support any types. So I would be ok with removing the `Object.keys(types).length > 1` check in this file, so that the dropdown always shows.

@chirimoya WDYT?

**Comment by danrot** [comment] 2020-03-23 08:04
@kfrohwein Can you deliver an example? We have just discussed it, and we were wondering what the use case for this is. If there is only one type for this block, the label of the block should actually be information. E.g. if I edit here a list of image galleries, I would label the entire block image gallery, and the type would probably also be called image gallery, showing the same text twice without any additional information.

**Comment by alexander-schranz** [comment] 2020-03-23 12:13
@danrot I think the problem is that the information (block title) is out of screen and thats why I think @kfrohwein wanted to have the information always be displayed and when having multiple blocks in the template the content manager get easily lost. So I also think it would make sense to show the type there.

**Comment by kfrohwein** [comment] 2020-03-24 14:37
If you have just one block type you are lost. I just saw that you can see the type if you close the block. Maybe I missed that before because of my screens color settings and the light grey didn't show on white.

In multiple blocks to me it is just a difference between a select box and the "active" selection. So there is no really strong impression about what you are currently editing.

All in all I can't remember a case when my content managers saw that as a problem. So in the end it might just be my impression.

Close or close not :)

**Comment by danrot** [comment] 2020-03-31 09:03
If this has not been mentioned by any of your content managers, I would say we leave it as it is for now. We still have the reference to this issue, so I think I am going to close it.

**Closed by danrot** 2020-03-31 09:03 UTC
Labels: Feature, To Discuss, UX
