### ISSUE TITLE
Add regenerate button for URL in page form

### ISSUE THREAD

**Issue by cdesign** [sulu/sulu#2452] opened 2016-06-05 18:09 UTC
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |

It would be helpful if Sulu auto-generated the content URL whenever the Title is changed _AND_ the 'resource locator' field is empty.

This would be particularly helpful for pages that are copied where the user is likely to change the page title after after the URL has been auto-generated by Sulu (during the copy operation). As it is now, after a copied page's Title is changed, the URL remains the same, and the user must re-enter the URL manually (if he/she wants the url to match the Title). If the user first clears the 'resource locator' field and then changes the Title, it would be nice if Sulu auto-generated the URL just as it does for a new page.

Another option would be to add a 'Generate url' button (next to the 'Show history' button) that auto-generates the URL. This would put the user in control of when this happens.

**Comment by wachterjohannes** [comment] 2016-06-06 05:43
we have already thought about a regenerate button - i think that would also help you?

**Comment by cdesign** [comment] 2016-06-06 07:17
Yes, that would do it.

**Comment by danrot** [comment] 2016-07-04 08:14
I change the title to @wachterjohannes proposal.

**Comment by danrot** [comment] 2020-04-20 05:52
Duplicate of #4221, therefore closing this one, becuase the other one has a better description of our proposed solution.

**Closed by danrot** 2020-04-20 05:52 UTC
Labels: Feature
