### ISSUE TITLE
MassiveSearch breaks when overwriting built in contact or account entity

### ISSUE THREAD

**Issue by wimulkeman** [sulu/sulu#5913] opened 2021-04-01 11:39 UTC
Q | A
-- | --
Sulu Version | 2.2.5
PHP Version | 7.2.20
DB Version | 5.7.32-35
Browser Version | - (issue on command line)

This story is a follow-up of #5897 

# Actual Behavior

In the project the Account entity has been extended following the guidelines at https://docs.sulu.io/en/2.2/cookbook/extend-entities.html.

When running the command `bin/console massive:search:reindex` the following error is thrown when indexing the accounts:

```
provider "doctrine_orm"

-- reindexing "8" instances of "Sulu\Bundle\ContactBundle\Entity\Account"
 0/8 [>---------------------------]   0%

In Account.php line 325:
  Return value of Sulu\Bundle\ContactBundle\Entity\Account::getAccountAddresses() must implement interface Doctrine\Common\Collections\Collection, null returned

massive:search:reindex [--batch-size BATCH-SIZE] [--provider PROVIDER]
```

This issue is given on getAccountAddresses, getPhones and getEmails.

# Expected Behavior

I expect to be able to extend Sulu entities and index the same entities using Massive Search without an error.

# Steps to Reproduce

1. Extend the Account entity using the steps described at https://docs.sulu.io/en/2.2/cookbook/extend-entities.html
2. Create a new account in admin under Contacts > Persons without an address or e-mail
3. Run bin/console massive:search:reindex

# Possible Solutions

A possible reason for this could be that the Sulu entities are hardcoded `massive-search-mapping` https://github.com/sulu/sulu/blob/2.x/src/Sulu/Bundle/ContactBundle/Resources/config/massive-search/Account.xml#L3

**Comment by alexander-schranz** [comment] 2021-04-01 11:45
@wimulkeman  Thank you for creating this Issue.

As mention by you the massive search `mapping` is the problem here. It loads the `abstract` `mapped-superclass` meta data from the core Account entity instead of the new metadata of the entity. Best would be that the `massve-search` supports here the usage of `AccountInterface` because the SuluPersistenceBundle would load over the AccountInterface the metadata from the correct entity. At current state jms/metadata reader need maybe be adjusted that this work, currently there is also strange need that the `.xml` need to have the same name like the Entity which is the cause that we can not easily switching to the Interface, here we would need to invest how the metadata is loaded and how we could use the interface to load the correct doctrine metadata.

**Comment by wimulkeman** [comment] 2021-04-01 12:11
@alexander-schranz Thanks for explaining the underlying points. I will dive into it a bit myself to familiarize myself with the inner workings of the mapping part. 

If I can help with anything let me know, I will try allocate some of my time to help with resolving the issue.

**Comment by alexander-schranz** [comment] 2021-05-10 10:04
This issue should be fixed with the latest MassiveSearchBundle Release: https://github.com/massiveart/MassiveSearchBundle/releases/tag/2.6.1

**Closed as completed by alexander-schranz** 2021-05-10 10:04 UTC
Labels: Bug
