### ISSUE TITLE
Manage target and anchor for page of type internal-link

### ISSUE THREAD

**Issue by rflorent** [sulu/sulu#3440] opened 2017-07-11 16:33 UTC
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

Hy,
It would be great if we could have the possibility to

- manage the target (self / blank) of a link (content page > parameters)
- add anchor part on a redirection (content page > parameters > target existing content page)

The cases I'm often facing : 
- create an anchor menu link (target one section on the homepage for example)
--> actually I create a content with an external link with an absolute url and a anchor, that's break the domain logic in the webspace definition.
--> we could have a input for the anchor when selecting "internal link"

![sulu-content-parameters](https://user-images.githubusercontent.com/8590540/28079101-659e985c-6667-11e7-8d5b-de14ef5c1ad7.jpg)

Thks

**Comment by danrot** [comment] 2017-07-17 09:27
We have already talked about this feature, but we are not sure yet how to implement it. We will put more thoughts into that in the 2.0 release.

**Comment by niklasnatter** [comment] 2021-03-12 13:38
Related to https://github.com/sulu/sulu/issues/5790

**Comment by niklasnatter** [comment] 2021-08-24 16:37
Thanks for reporting! I am closing this as a duplicate of https://github.com/sulu/sulu/issues/3051

**Closed by niklasnatter** 2021-08-24 16:37 UTC
Labels: Feature, Needs Information
