### ISSUE TITLE
Indexing of document versions

### ISSUE THREAD

**Issue by andreasganahl** [sulu/sulu#3642] opened 2017-11-22 14:07 UTC
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.6 or ealier
| Browser Version | not relevant

#### Actual Behavior

At the the moment earlier versions of documents are still available through url. if a document is indexed by the search engine its really hard to get them out of the index.

#### Expected Behavior

older versions of documents can marked for example as "no index" or "private mode"
older versions are still avalaible through media management in sulu
i case a newer version will be uploaded, the older version gets a new url or will be redirected to the newest version

**Comment by danrot** [comment] 2019-11-28 14:28
Cannot reproduce. I only get the latest version of a media, so I am going to close this issue.

**Closed by danrot** 2019-11-28 14:28 UTC
