### ISSUE TITLE
Irregular connection resets on XAMPP 7.0.8 for windows

### ISSUE THREAD

**Issue by nnatter** [sulu/sulu#2570] opened 2016-07-11 11:51 UTC
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 6e7e1af52a29d18a606b0aaf81f71292681a26aa |
| Browser Version | tested with Chrome 51 & IE11 |
#### Actual Behavior

Connection reset errors are occuring sporadically while using sulu on XAMPP 7.0.8 for windows.
The errors are leading to missing datagrids. Errors are occuring especially in the media- and contact bundle.

![](https://picload.org/image/rrdlrilo/reset.png)

XAMPP 7.0.8 uses the following services:
Apache 2.4.18, MariaDB 10.1.13, PHP 7.0.8, phpMyAdmin 4.5.1, OpenSSL 1.0.2

Sulu works fine on XAMPP 5.6.23 which uses:
Apache 2.4.17, MariaDB 10.1.13, PHP 5.6.23, phpMyAdmin 4.5.1, OpenSSL 1.0.2
#### Steps to Reproduce

Install sulu on a XAMPP 7.0.8 environment, login, open the contact bundle ui.

**Comment by danrot** [comment] 2017-02-13 08:03
@nnatter I think that issue doesn't make any sense here...That sounds like an issue with your webserver configuration and not sulu related at all... Apart from that we can't really work on that, since it is not reproducable for us 😕 So I think I am going to close this issue.

**Closed by danrot** 2017-02-13 08:03 UTC
