### ISSUE TITLE
URL Content Type - Bug with schemes

### ISSUE THREAD

**Issue by thomasduenser** [sulu/sulu#2673] opened 2016-07-25 15:05 UTC
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.3 |
#### Actual Behavior

When using the property type `url` with the pre-defined `schemes`, it always displays `http` after saving the page for the first time. The GET Request returns the correct value and it is saved correctly ...

I'm using following configuration in my xml file:

```
<property name="url" type="url">
    <meta>
        <title lang="en">URL</title>
    </meta>

    <params>
        <param name="defaults" type="collection">
            <param name="scheme" value="http://"/>
            <param name="specific_part" value="www.google.at"/>
        </param>
        <param name="schemes" type="collection">
            <param name="http://"/>
            <param name="https://"/>
            <param name="//"/>
        </param>
    </params>
</property>
```
#### Expected Behavior

That the URL field displays the correct value which is saved correctly.
#### Steps to Reproduce

Add the property like above in a template, save the page and refresh.

**Comment by nickvanderzwet** [comment] 2017-02-06 10:51
It seems the "//" param is causing this error.. Everything seems to work well without this option.

**Comment by wachterjohannes** [comment] 2017-02-06 11:55
the problem is in this file: https://github.com/massiveart/husky/blob/develop/husky_services/url-validator.js#L27

It relies on the `//` to validate the scheme

**Comment by danrot** [comment] 2019-11-07 08:13
This seems to work in Sulu 2.0, so I am going to close this issue.

**Closed by danrot** 2019-11-07 08:13 UTC
Labels: Bug
