### ISSUE TITLE
Homepage doesn't show up in navigation

### ISSUE THREAD

**Issue by ZeeCoder** [sulu/sulu#2734] opened 2016-08-03 09:29 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.2
| Browser Version | Chrome latest

#### Actual Behavior

The homepage doesn't appear in any of the navigation contexts I added it to.

#### Expected Behavior

It should appear wherever I add it, like the way normal pages behave.

#### Steps to Reproduce

Create a navigation context called "main".
In twig, iterate over `sulu_navigation_root_tree('main')` to print out the attached pages.
Add the homepage to the "main" navigation context.
Check if it appears.
Try to add a regular page to the same context, and it will appear.

**Comment by ZeeCoder** [comment] 2016-08-03 09:31
I found one workaround.
I can create an internal link content pointing to the homepage, and then configure that internal link to appear in the navigation contexts.

Still annoying that I cannot just do the same from the homepage's settings. :/

**Comment by danrot** [comment] 2016-08-03 11:17
That's a duplicate of #1527, see the discussion there. It's hard to say what should happen in this case, because if you load the navigation as tree, the top level would consist only of the home page (because our content is structured the way, you can think of the homepage as the base node). If you have anything to add, please participate in the discussion of the other issue.

**Closed by danrot** 2016-08-03 11:17 UTC
