### ISSUE TITLE
sulu build gives getProperties on null

### ISSUE THREAD

**Issue by nvdbeek** [sulu/sulu#3517] opened 2017-09-13 13:18 UTC
Running Sulu (used sulu-minimal) 1.6.3 on PHP 7.0.1 and Symfony 3.3.8.

When I run sulu:build dev the following step "sulu_core.webspace.document_manager.webspace_initializer [+] homepage: [homepage] /cmf/example/contents (nl)" gives: 

`Call to a member function getProperties() on null.`

`
Exception trace:
() at /vendor/sulu/sulu/src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php:319
 Sulu\Component\Content\Document\Subscriber\StructureSubscriber->mapContentToNode() at /vendor/sulu/sulu/src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php:230
Sulu\Component\Content\Document\Subscriber\StructureSubscriber->saveStructureData() at n/a:n/a
call_user_func() at /vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:212
`

What am I missing and how to fix it?

**Comment by trickreich** [comment] 2017-09-13 13:32
@nvdbeek Can you show us your webspaces config?

**Comment by nvdbeek** [comment] 2017-09-13 13:40
```
<?xml version="1.0" encoding="utf-8"?>
<webspace xmlns="http://schemas.sulu.io/webspace/webspace"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/webspace/webspace http://schemas.sulu.io/webspace/webspace-1.1.xsd">

    <name>example.nl</name>
    <key>example</key>

    <localizations>
        <localization language="nl" default="true"/>
    </localizations>

    <default-templates>
        <default-template type="page">default</default-template>
        <default-template type="home">homepage</default-template>
    </default-templates>

    <navigation>
        <contexts>
            <context key="main">
                <meta>
                    <title lang="nl">Hoofdmenu</title>
                </meta>
            </context>
        </contexts>
    </navigation>

    <portals>
        <portal>
            <name>example.nl</name>
            <key>example</key>

            <environments>
                <environment type="prod">
                    <urls>
                        <url language="nl">{host}</url>
                    </urls>
                </environment>
                <environment type="stage">
                    <urls>
                        <url language="nl">{host}</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url language="nl">{host}</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
</webspace>

```

**Comment by trickreich** [comment] 2017-09-13 13:41
@nvdbeek Whats the name of the file?

**Comment by nvdbeek** [comment] 2017-09-13 13:42
@trickreich example.nl.xml

**Comment by trickreich** [comment] 2017-09-13 13:45
Cache cleared? Where does this came from `letselhulpservice`?
You've tried to run `bin/adminconsole sulu:build dev  --destroy`?

**Comment by danrot** [comment] 2017-09-13 13:51
That's usually an issue with a template, not the webspace. Can you show all your template configurations?

**Comment by nvdbeek** [comment] 2017-09-13 13:59
Sorry @trickreich that was the old name. Before it was letselhulpservice, but now it is example .

@danrot 
templates/pages/homepage.xml
```
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>homepage</key>

    <view>templates/homepage</view>
    <controller>SuluWebsiteBundle:Default:index</controller>
    <cacheLifetime>2400</cacheLifetime>

    <meta>
        <title lang="nl">Homepage</title>
    </meta>

    <properties>
        <section name="highlight">
            <properties>
                <property name="title" type="text_line" mandatory="true">
                    <meta>
                        <title lang="nl">Title</title>
                    </meta>
                    <params>
                        <param name="headline" value="true"/>
                    </params>

                    <tag name="sulu.rlp.part"/>
                </property>

                <property name="url" type="resource_locator" mandatory="true">
                    <meta>
                        <title lang="nl">Resourcelocator</title>
                    </meta>

                    <tag name="sulu.rlp"/>
                </property>
            </properties>
        </section>

        <property name="article" type="text_editor">
            <meta>
                <title lang="nl">Article</title>
            </meta>
        </property>
    </properties>
</template>
```
templates/pages/default.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>default</key>

    <view>templates/default</view>
    <controller>SuluWebsiteBundle:Default:index</controller>
    <cacheLifetime>2400</cacheLifetime>

    <meta>
        <title lang="nl">Default</title>
    </meta>

    <properties>
        <section name="highlight">
            <properties>
                <property name="title" type="text_line" mandatory="true">
                    <meta>
                        <title lang="nl">Title</title>
                    </meta>
                    <params>
                        <param name="headline" value="true"/>
                    </params>

                    <tag name="sulu.rlp.part"/>
                </property>

                <property name="url" type="resource_locator" mandatory="true">
                    <meta>
                        <title lang="nl">Resourcelocator</title>
                    </meta>

                    <tag name="sulu.rlp"/>
                </property>
            </properties>
        </section>

        <property name="article" type="text_editor">
            <meta>
                <title lang="nl">Article</title>
            </meta>
        </property>
    </properties>
</template>

**Comment by wachterjohannes** [comment] 2017-09-14 12:31
@nvdbeek are you sure that the html templates for this xml templates?

**Comment by nvdbeek** [comment] 2017-09-15 09:59
@wachterjohannes how do you mean your comment?

When I run the command sulu:content:validate he gives no errors.

**Comment by wachterjohannes** [comment] 2017-09-15 12:06
@nvdbeek the problem is that the database is not initialized. this will be done inside the `sulu:build` command. sulu uses the html.twig template which is defined in the XML template to validate if the template is valid in this webspace. are you sure you have a `templates/homepage.html.twig` file?

**Comment by nvdbeek** [comment] 2017-09-15 13:50
Hello @wachterjohannes , under templates I have a homepage.html.twig but still getting the error `Call to a member function getProperties().`

Structure:
Resources:
- templates
-- pages
--- default.xml
--- homepage.xml
-- snippets
--- default.xml
- views
-- templates
--- default.html.twig
--- homepage.html.twig
- webspaces
example.nl.xml

**Comment by wachterjohannes** [comment] 2017-09-19 07:29
hmm ... I had rebuild your setup and I didn't get this exception. can you try to debug why the structure is null?

**Comment by nvdbeek** [comment] 2017-09-19 09:08
Thank you for testing it @wachterjohannes. I have solved the problem.. it was a mistake.. I forget to set the right folders (Resources/pages to Resources/templates/pages) in my config.

Is it possible that the admin panel stays on the loading page? He will not go to the admin overview and there are no errors.

**Comment by wachterjohannes** [comment] 2017-09-19 12:08
no problem :) i will close this issue - thanks for the feedback why you had this problem.

**Closed by wachterjohannes** 2017-09-19 12:08 UTC
