### ISSUE TITLE
Enable to overwrite FormatManager by service definition in yaml

### ISSUE THREAD

**Issue by rs2487** [sulu/sulu#6091] opened 2021-05-31 14:56 UTC
| Q | A
| --- | ---
| Sulu Version | 2.2.6
| PHP Version | 7.4
| DB Version | 
| Browser Version | 

# Actual Behavior

Can't overwrite `Sulu\Bundle\MediaBundle\Media\FormatManager\FormatManager` by own services.yaml because Symfony will inject `%sulu_media.format_cache.save_image%` as  `"1"`. The default usage of xml injects `"true"`.
 
# Expected Behavior

I can overwrite the FormatManager by using yaml.

# Steps to Reproduce
Add to services.yaml

```
    sulu_media.format_manager:
        class: Sulu\Bundle\MediaBundle\Media\FormatManager\FormatManager
        public: true
        arguments:
            - '@sulu.repository.media'
            - '@sulu_media.format_cache'
            - '@sulu_media.image.converter'
            - '%sulu_media.format_cache.save_image%'
            - '%sulu_media.format_manager.response_headers%'
            - '%sulu_media.image.formats%'
            - '@?logger'
```

# Possible Solutions

```
    public function __construct(
        MediaRepositoryInterface $mediaRepository,
        FormatCacheInterface $formatCache,
        ImageConverterInterface $converter,
        $saveImage,
        $responseHeaders,
        $formats,
        LoggerInterface $logger = null
    ) {
        $saveImage = 'true' === $saveImage || '1' === $saveImage;
        
        $this->mediaRepository = $mediaRepository;
        $this->formatCache = $formatCache;
        $this->converter = $converter;
        $this->saveImage = $saveImage;
        $this->responseHeaders = $responseHeaders;
        $this->fileSystem = new Filesystem();
        $this->formats = $formats;
        $this->logger = $logger ?: new NullLogger();
    }
```

**Comment by niklasnatter** [comment] 2021-06-01 07:39
Hey,
thanks for reaching out. Unfortunately, I cannot reproduce this with Sulu 2.3.0 and Symfony 5.2.7. 

I have added the following lines to my `services.yaml`:

```yaml
services:
    # ...
    sulu_media.format_manager:
        class: Sulu\Bundle\MediaBundle\Media\FormatManager\FormatManager
        public: true
        arguments:
            - '@sulu.repository.media'
            - '@sulu_media.format_cache'
            - '@sulu_media.image.converter'
            - '%sulu_media.format_cache.save_image%'
            - { 'test-header': 'test-value' }
            - '%sulu_media.image.formats%'
            - '@?logger'
```

This leads to the following arguments to the constructor of the service:
![Screenshot 2021-06-01 at 09 38 19](https://user-images.githubusercontent.com/13310795/120285012-22991f80-c2bd-11eb-847e-df5bf8d3003f.png)

**Comment by alexander-schranz** [comment] 2021-06-04 10:30
@rs2487 for me it looks like that your `save_image` is an environment variable. All environment variables are strings and can be converted to other types using e.g.: `%env(int:...)%` or `%env(bool:...)%` more about that in the Symfony Env Variable Processor documentation: https://symfony.com/doc/current/configuration/env_var_processors.html#built-in-environment-variable-processors

**Comment by rs2487** [comment] 2021-06-07 05:35
@alexander-schranz no it is not a environment variable. It uses the default from the bundle.

**Comment by niklasnatter** [comment] 2021-06-07 07:38
Could you provide a repository that allows us to reproduce the problem? 
I am afraid we cannot help you with this until we are able to reproduce the problem.

**Comment by alexander-schranz** [comment] 2021-06-16 07:54
@rs2487 we can not reproduce this. Not sure where this variable come in your case and why its a string, could also be that you are on an old symfony version? I will close this issue, because if it would it happens I think it would be a bug on symfony side with dependency injection, maybe an symfony update helps in your case.

**Closed as completed by alexander-schranz** 2021-06-16 07:54 UTC
Labels: Bug
