### ISSUE TITLE
Add snippet from template

### ISSUE THREAD

**Issue by Doum-Super** [sulu/sulu#2154] opened 2016-03-22 07:54 UTC
How can you use Sulu\Component\DocumentManager\DocumentManager in my controller for add snippet data from template form ?

**Comment by wachterjohannes** [comment] 2016-03-22 12:30
could you please explain you problem more in detail. Additionally please use our issue template otherwise we cannot categories you issue properly.

**Comment by wachterjohannes** [comment] 2016-05-18 15:39
as we dont here anything from @Doum-Super i will close this issue because i have no idea what the problem is. @Doum-Super feel free to reopen it if is still an issue for you, but then we need some more information. then we can help you :)

**Closed by wachterjohannes** 2016-05-18 15:39 UTC
Labels: Question
