### ISSUE TITLE
Text editor params are not working

### ISSUE THREAD

**Issue by rogoit** [sulu/sulu#4404] opened 2019-01-30 22:28 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Actual dev
| Browser Version | Actual chrome

#### Actual Behavior

You can insert tables and no links. 

#### Expected Behavior

You can add links and no table.

#### Steps to Reproduce

See screenshot

#### Possible Solutions
![bildschirmfoto von 2019-01-30 23-24-00](https://user-images.githubusercontent.com/3101439/52017160-ce13e880-24e6-11e9-8307-3bc40d5174d4.png)

**Comment by alexander-schranz** [comment] 2019-10-11 00:30
@rogoit sorry for the late response. This parameters do not longer exist because we upgraded to CKEditor 5.
Please let us know what kind of texteditor you want to display.

**Comment by danrot** [comment] 2019-12-05 20:00
I would say this is a duplicate of #4898. We won't be able to offer the exact same configurations as previously, because we've updated the CKEditor...

**Closed by danrot** 2019-12-05 20:00 UTC
