### ISSUE TITLE
smart content in a snippet

### ISSUE THREAD

**Issue by rflorent** [sulu/sulu#3005] opened 2016-10-27 21:48 UTC
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3.0 |
| Browser Version | Firefox 49.0.2, Safari, Chrome... |
#### Actual Behavior

When choosing the data source, the tree content load forever.
Console show an js error : 
TypeError: n._embedded is undefined
...ar r=this.sandbox.dom.find("ul",e),i,s;this.sandbox.util.each(n._embedded[this.o...
#### Expected Behavior

the tree should be display
#### Steps to Reproduce

Create a snippet type with a smart content, add a new snippet and choose the source

**Comment by rflorent** [comment] 2016-10-27 22:05
Issue is related to #2954

**Comment by danrot** [comment] 2016-11-07 13:36
@rflorent It is also a duplicate of #2939, so I am closing this one. Please follow the other issue.

**Closed by danrot** 2016-11-07 13:36 UTC
Labels: Duplicate
