### ISSUE TITLE
PageDocument not indexable with block-types.

### ISSUE THREAD

**Issue by dominikmatt** [sulu/sulu#3274] opened 2017-03-23 09:10 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5.2

#### Actual Behavior

After running `bin/websiteconsole massive:search:index:rebuild` we get an error.
```
 [Elasticsearch\Common\Exceptions\BadRequest400Exception]
  mapper_parsing_exception: Field name [blocks0blocks.headline] cannot contain '.'
```

#### Steps to Reproduce

- Create a block with ` index="true"` in your template:
```
<block name="blocks" default-type="textImage" minOccurs="0">
<types>
    <type name="textImage">
        <properties>
            <property name="headline" type="text_line">
                <tag name="sulu.search.field" index="true"/>
            </property>
        </properties>
    </types>
</block>
```
- Run rebuild index command. This rebuild will exit with the error above.

**Comment by danrot** [comment] 2017-05-08 15:34
@dominikmatt Can you please execute the command with the `-v` flag, and post the error with the stack trace?

**Comment by danrot** [comment] 2017-05-08 15:35
And does that only happen on the command line, or also when saving a page?

**Comment by danrot** [comment] 2017-05-08 15:49
I have tested it with the zend lucene implementations, and it is working there. The problem is that we rely on the `PropertyAccessor` component from Symfony when [reading the values](https://github.com/massiveart/MassiveSearchBundle/blob/develop/Search/Metadata/FieldEvaluator.php#L86). And it looks to me like this information is also indexed, but elasticsearch doesn't seem to like `.` as names 😕 Have to make sure tomorrow that this part is really indexed.

**Comment by wachterjohannes** [comment] 2017-05-09 05:33
@danrot yes names with a dot inside are not allowed. the dot if reserved for nested objects or sub-fields. we have to find another delimiter here.

**Comment by danrot** [comment] 2017-05-09 06:18
That's the whole point: We can't just change the delimiter, because we are using the `PropertyAccessor`, which requires the dot to be there.

**Comment by danrot** [comment] 2017-05-11 11:18
Fixed in https://github.com/massiveart/MassiveSearchBundle/pull/107

**Closed by danrot** 2017-05-11 11:18 UTC
Labels: Bug
