### ISSUE TITLE
Notice causes an error in rest call

### ISSUE THREAD

**Issue by DjangoFR** [sulu/sulu#4480] opened 2019-03-11 09:54 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.x-dev c478140
| Browser Version | Chrome Version 72.0.3626.109 (Official Build) (64-bit)

#### Actual Behavior

Request to the following url causes an error http://sulu.local/admin/api/pages?exclude-ghosts=false&exclude-shadows=false&locale=de&webspace=zmf&expandedIds=6e8e8021-2fa7-4a99-8c40-2ea7ddb23a34&fields=id%2Ctitle%2Corder%2Cpublished&flat=true

#### Expected Behavior

Handle error "ErrorException: Notice: Undefined index: _embedded in..."

`{
    "code": 0,
    "message": "Notice: Undefined index: _embedded",
    "errors": [
        "ErrorException: Notice: Undefined index: _embedded in /var/www/project/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Controller/PageController.php:75\nStack trace:\n#0 /var/www/project/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Controller/PageController.php(42): Sulu\\Bundle\\PageBundle\\Controller\\PageController->transformResponse(Object(Symfony\\Component\\HttpFoundation\\Response))\n#1 /var/www/project/vendor/symfony/http-kernel/HttpKernel.php(150): Sulu\\Bundle\\PageBundle\\Controller\\PageController->cgetAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /var/www/project/vendor/symfony/http-kernel/HttpKernel.php(67): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#3 /var/www/project/vendor/symfony/http-kernel/Kernel.php(198): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#4 /var/www/project/public/index.php(75): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#5 {main}"
    ]
}`

#### Possible Solutions

Tmp. solution could be to "deactivate notices" but long term solution should be done in the sulu code.

**Comment by danrot** [comment] 2019-12-06 11:34
What is the exact problem here? The link is not really useful... Can you provide steps to reproduce this error?

**Comment by danrot** [comment] 2019-12-10 16:24
Closing because not reproducable.

**Closed by danrot** 2019-12-10 16:24 UTC
