### ISSUE TITLE
Smart content medie doesn't sort by title

### ISSUE THREAD

**Issue by thgie** [sulu/sulu#5139] opened 2020-03-25 10:00 UTC
| Bug? | yes
| Sulu Version | 2.0.4
| Browser Version | Chrome 80.0.3987.149

#### Actual Behavior

Smart content with _provider_ media doesn't sort by title. Changing direction has no effect.

#### Expected Behavior

Should sort :)

**Comment by thgie** [comment] 2020-03-26 08:30
Thank you for the hint :) Will move the report over there.

**Comment by danrot** [comment] 2020-03-26 09:41
Duplicate of #5142

**Closed by danrot** 2020-03-26 09:41 UTC
