### ISSUE TITLE
Login keyboard navigation not working on Edge

### ISSUE THREAD

**Issue by nnatter** [sulu/sulu#2822] opened 2016-08-17 06:34 UTC
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3 |
| Browser Version | Microsoft Edge 25.10586 |
#### Actual Behavior

The login screen is not navigatable only by keyboard with Microsoft Edge.
1. Load login screen 
2. The username field is selected (do no click it with the mouse)
3. Press Tab
4. The password field is **not** selected
#### Expected Behavior

When pressing tab and username field is selected, password field should be selected afterwards.
#### Possible Solutions

Changing selection with tab works after selecting the username field with a mouseclick. Probably the selection is not set the right way when intializing.

**Comment by alexander-schranz** [comment] 2019-10-11 00:53
Can't reproduce anymore. Seems to be fixed in 1.6

**Closed by alexander-schranz** 2019-10-11 00:53 UTC
Labels: Bug, UX
