### ISSUE TITLE
PHP Warnings when executing "sulu:build search_index"

### ISSUE THREAD

**Issue by fdyckhoff** [sulu/sulu#3854] opened 2018-03-17 22:04 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | v1.6.14
| Browser Version | -
| PHP Version | 7.0.25

#### Actual Behavior

When executing following command, the console output is disrupted by PHP Warnings (PHP 7.0):

```Shell
php bin/adminconsole sulu:build search_index 
```

> PHP Warning:  str_repeat(): Second argument has to be greater than or equal to 0 in /path/to/project/vendor/symfony/symfony/src/Symfony/Component/Console/Helper/ProgressBar.php on line 512

[sulu-build-search-index-console-warning-with-debug-info.txt](https://github.com/sulu/sulu/files/1822133/sulu-build-search-index-console-warning-with-debug-info.txt)

When executing with --env=prod the warnings are only displayed and the command proceeds.
*When executing with --env=dev the command fails.*

The warnings appear only for some of the sulu documents and doctrine entities (e.g. FileVersionMeta and PageDocument).
The warnings do not appear, when executing the reindex-command directly (`massive:search:reindex`).

#### Expected Behavior

The command can be executed without warnings.

#### Steps to Reproduce

I'm not sure yet, how to reproduce this. I didn't have any warnings at the beginning (fresh installation with initial content / `sulu:build dev`). The warnings occurred some time after editing and adding more content.

**Comment by wachterjohannes** [comment] 2018-03-20 13:22
@fdyckhoff could you please add the full output of your console to see how many documents you have?

**Comment by wachterjohannes** [comment] 2018-03-21 10:23
hmm that's weird ... cannot reproduce that on my machine - seems an error when initializing the progress-bar - i will investigate time as soon as possible - will give you some feedback

**Comment by fdyckhoff** [comment] 2018-03-24 17:21
I found a solution. see https://github.com/massiveart/MassiveBuildBundle/pull/14

The problem was, that the ProgressBar tries to calculate the length of the undecorated message in this line: https://github.com/symfony/console/blob/master/Helper/ProgressBar.php#L427

But the MassiveOutputFormatter currently does not implement the case that a message shall be undecorated. The length of the message will be calculated including the extra spaces for indentation and `$emptyBars` can turn into a negative value, which is not allowed to be used as multiplier for `str_repeat` in the next line.

**Comment by wachterjohannes** [comment] 2018-03-24 19:20
👍 thanks for investigating time for this issue! the PR looks good and i will try that on monday before merging 😀

**Comment by trickreich** [comment] 2018-03-26 11:04
Issue was fixed in https://github.com/massiveart/MassiveBuildBundle/pull/14

**Closed by trickreich** 2018-03-26 11:04 UTC
