### ISSUE TITLE
view rights in media area

### ISSUE THREAD

**Issue by andreasganahl** [sulu/sulu#3837] opened 2018-03-12 12:39 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6
| Browser Version | every browser

#### Actual Behavior

A user do only have full rights to see one collection in the media area (not system)
if he choose "media" in the left menu, the user can see all media in the collection "all media"...!?

#### Expected Behavior

I think he should only see the items, which are in this collection (and children collections?)

**Comment by danrot** [comment] 2018-03-12 15:14
I think that this is a duplicate of #3822

**Closed by danrot** 2018-03-12 15:14 UTC
