### ISSUE TITLE
Error in sulu_resolve_media function after upgrading sulu and doctrine packages

### ISSUE THREAD

**Issue by floscom** [sulu/sulu#7138] opened 2023-08-14 07:49 UTC
| Q | A
| --- | ---
| Sulu Version | 2.4.14
| PHP Version | 8.0.7
| DB Version | 5.7.33
| Browser Version | Google Chrome 115.0.5790.170

# Actual Behavior

Sulu version: 2.4.14 (upgraded from 2.4.13)
Doctrine ORM version: 2.16.1 (upgraded from 2.15.4)
Doctrine Bundle version: 2.10.2 (upgraded from 2.10.1)

After upgrading the sulu, doctrine/orm, and doctrine/doctrine-bundle packages, the sulu_resolve_media function is producing an error. The exception thrown during the rendering of a template is:

`An exception has been thrown during the rendering of a template ("The given entity of type 'Sulu Bundle Tag-Bundle\Entity Tag' (| has no identity/no id values set. It cannot be added to the identity map.").
`

# Expected Behavior

The function should execute without errors.

# Steps to Reproduce

1. Upgrade sulu from 2.4.13 to 2.4.14.
2. Upgrade doctrine/orm from 2.15.4 to 2.16.1.
3. Upgrade doctrine/doctrine-bundle from 2.10.1 to 2.10.2.
4. Execute the code involving the sulu_resolve_media function.

# Possible Solutions

This might be related to changes in the upgraded packages, and an investigation into the interdependencies might reveal the root cause.  The solution is not known at this moment, further investigation is needed. 

We downgraded to the versions:
Sulu version: 2.4.13
Doctrine ORM version:2.15.4
Doctrine Bundle version: 2.10.1

**Comment by alexander-schranz** [comment] 2023-08-14 08:07
This error should if its a new error be reported to the doctrine/orm. Keep in mind 2.16.0 and newer versions are not yet compatible with doctrine/orm also because of this issue: https://github.com/doctrine/orm/issues/10869

**Comment by mpdude** [comment] 2023-08-15 13:19
The same error message has also been reported in https://github.com/doctrine/orm/issues/10889. We're still clueless where this might come from. If you can provide a reproduce case, this would be very much appreciated.

**Comment by YetiCGN** [comment] 2023-09-12 08:37
Same problem, declaring a conflict with `"doctrine/orm": ">=2.16"` solved this for the moment. Will Sulu declare conflicting versions once this issue is resolved and we know the final version range that's not compatible?

**Comment by mpdude** [comment] 2023-09-12 10:40
Jörn, do you think you can help finding a reproducer?

**Comment by YetiCGN** [comment] 2023-09-12 10:53
> Jörn, do you think you can help finding a reproducer?

I am not hopeful that I can. It's occuring deep in the SuluMediaBundle with a FormatOptions entity. Already spent half a day figuring out that the recent package upgrade was the culprit.

**Comment by alexander-schranz** [comment] 2023-09-12 11:04
@YetiCGN we sure will change the conflict as soon as we are sure sulu is again compatible with latest doctrine changes. I already created a more meta ticket for it here: https://github.com/sulu/sulu/issues/7142. @sylius is currently doing the same thing as they run into similar issues: https://github.com/Sylius/Sylius/blob/ba36584300e8df398c841c3a292a1d57e129fc1c/composer.json#L189.

Currently it is more lack of time to deeply analyze the things and bring reproducable tests directly into the `doctrine/orm` then without it we can not guarantee that it will happen again. What sulu diff from a normal doctrine/orm project is sure usage of gedmo tree extensions (gedmo issue init always all listeners), heavy usage of `resolveTargetListener` `Interface` -> `Entity`/overwritten`Entity`, usage of `postPersist` write things based on postIdGenerator. Not sure if that helps @mpdude.

**Comment by alexander-schranz** [comment] 2024-06-27 16:26
This should now be fixed with doctrine/orm 2.19.6: https://github.com/doctrine/orm/releases/tag/2.19.6 by https://github.com/doctrine/orm/pull/11194

**Closed as completed by alexander-schranz** 2024-06-27 16:26 UTC
Labels: Bug
