### ISSUE TITLE
Preview in Media-Selection

### ISSUE THREAD

**Issue by Jace25** [sulu/sulu#2540] opened 2016-07-05 12:32 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | dev

#### Actual Behavior

When adding new documents to a media selection, they will first be not visible. But when i browse into another collection and back to the previous collection, where i added the document it is visible. If i choose one of the previously added files, it seems that it is chosen, but when closing the collectionsview the chosen file is not visible. The property statet "Keine Medien ausgewählt". If i do some dump inside the twig template, i see all the ids of my files, i have chosen inside this property, so i think its some backend only behavior.

No Files chosen:
![image](https://cloud.githubusercontent.com/assets/4090694/16584509/c0f34f06-42bc-11e6-90fd-02904df4da25.png)

Added some Documents:
![image](https://cloud.githubusercontent.com/assets/4090694/16584523/d68d532a-42bc-11e6-9416-8459ad5c7186.png)

View after closing the media selection:
![image](https://cloud.githubusercontent.com/assets/4090694/16584528/de28f1a2-42bc-11e6-8ad6-ad6af42a01e2.png)

Some twig dumping:
![image](https://cloud.githubusercontent.com/assets/4090694/16584570/13a40858-42bd-11e6-82bd-c48e60b4eefe.png)

#### Expected Behavior

Some preview should be visible. 

#### Steps to Reproduce

See Screenshots above.

**Comment by danrot** [comment] 2016-07-12 09:40
The problem is that there are no previews generated for documents... Could you save the page? When I tried to reproduce this the server responded with a 500 error code saying:
```
"Search image format "170x170" is not known"
```

**Comment by Jace25** [comment] 2016-07-26 08:29
@danrot, sorry!

With the latest sulu dev, i am able to add files, to save the article and i also could view them while editing:
![image](https://cloud.githubusercontent.com/assets/4090694/17130979/843d4142-531b-11e6-933c-91e7b7fbe1b2.png)

![image](https://cloud.githubusercontent.com/assets/4090694/17130983/8aef2f3c-531b-11e6-8b63-bf24e21cca92.png)

![image](https://cloud.githubusercontent.com/assets/4090694/17130999/988edc46-531b-11e6-9e6e-d1ba2d04ee92.png)

So i think this issue is solved somehow with the latest changes?

**Comment by danrot** [comment] 2016-07-26 08:36
Yeah, if it works for you we can close this issue :-)

**Closed by danrot** 2016-07-26 08:36 UTC
Labels: Bug
