### ISSUE TITLE
template xml, property colspan causes design bug

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#2276] opened 2016-04-11 07:51 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | c9ff1bbfa3c7b3b7c33b9c2ce7b43ac7d251eb42
| Browser Version | all browsers

#### Actual Behavior

If you use colspan on properties in the template xml the margin-top of some grid items is missing. 

#### Expected Behavior

Right margin-top on grid elements with colspan

#### Steps to Reproduce

![bildschirmfoto 2016-04-11 um 09 49 08](https://cloud.githubusercontent.com/assets/8446502/14420166/ad1f1e54-ffca-11e5-9802-bd6bb32d1657.png)

![bildschirmfoto 2016-04-11 um 09 49 52](https://cloud.githubusercontent.com/assets/8446502/14420178/c76019ee-ffca-11e5-9e15-ed9c9a75a110.png)

**Comment by danrot** [comment] 2016-04-15 07:43
Duplicate of https://github.com/sulu/sulu/issues/646

**Closed by danrot** 2016-04-15 07:43 UTC
Labels: Bug, Critical, Duplicate
