### ISSUE TITLE
Adding and removing elements to teaser selection behaves strange

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#5412] opened 2020-07-15 11:25 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.33

#### Actual Behavior

By adding more then one page, there is always one page less added to the content-type then selected.
When removing pages in the overlay from the content-type. It still shows those pages.
Same when deleting them in the content-type, saving and reloading the browser.

#### Expected Behavior

Korrekt behavior after selecting, unselecting pages.

#### Steps to Reproduce

Add teaser_selection content-type to a page and start adding / removing pages from it.

**Comment by wachterjohannes** [comment] 2020-07-15 19:25
@Quehnie cannot reproduce it with published pages - but when you select a unpublished page this will not be shown in the teaser-list. could this be the problem?

**Comment by danrot** [comment] 2020-08-25 15:34
Fixed in #5415

**Closed by danrot** 2020-08-25 15:34 UTC
Labels: Bug
