### ISSUE TITLE
Permission denied when executing a command to populate the database with Sulu’s default data

### ISSUE THREAD

**Issue by gonliSs** [sulu/sulu#3049] opened 2016-11-29 02:20 UTC
| Q | A
| --- | ---
| Bug? | yes
| Sulu Version | sulu/sulu-minimal (1.4.2)

I installed Sulu first as a root then as a user with root privileges each time following these steps:
1) Created a folder in /var/www (`cd /var/www; mkdir gen`)
2) Bootstrapped a new project using sulu/sulu-minimal (`composer create-project sulu/sulu-minimal gen -n`)
3) Changed file app/Resources/webspaces/example.com.xml name to app/Resources/webspaces/gen.xml (`cd gen/app/Resources/webspaces/; mv example.com.xml gen.xml`)
4) Changed `<name>My Project</name>
    <key>my-project</key>`
to `<name>Gen</name>
    <key>gk</key>`
(nano gen.xml)
5) Changed database data (`cd ../../config; nano parameters.xml`)
6) Tried to populate Sulu with default data by running 
`bin/adminconsole sulu:build dev`
from directory: /var/www/gen 
and got an error:
`-bash: bin/adminconsole: Permission denied`

What is causing this?

**Comment by jbfewo** [comment] 2016-11-30 15:27
Could you check, if you have the rights to _execute_ you adminconsole? Maybe paste the output of `ls -lah bin/`

**Comment by gonliSs** [comment] 2016-11-30 23:53
I didn't. I thought it'd be all set up after installation. Seems I need to learn a lot still...

**Comment by danrot** [comment] 2016-12-16 08:06
I think that's the same issue as in https://github.com/sulu/sulu-docs/issues/265... There's nothing we can do about this, except adding this part to the documentation...

@gonliSs Have you managed to get it working now?

**Comment by danrot** [comment] 2017-02-13 08:11
Closing as duplicate of sulu/sulu-docs#265

**Closed by danrot** 2017-02-13 08:11 UTC
Labels: Needs Information
