### ISSUE TITLE
IntlMessageFormat dependency drop support to old Safari version

### ISSUE THREAD

**Issue by Adelysnet** [sulu/sulu#6597] opened 2022-05-09 10:04 UTC
| Q | A
| --- | ---
| Sulu Version | 2.4.2
| Browser Version | Safari 13.1.2

Sulu Admin is not loading in safari prior version 14 ( not tested on iOS, but seems not supported before IOS 14) : `Unhandled Promise Rejection: TypeError: undefined is not a constructor (evaluating 'new Intl.Locale(t[0])')` at core.js:188 thrown by the IntlMessageFormat library.

More infos on compatibility here : https://caniuse.com/?search=intl.locale

**Comment by alexander-schranz** [comment] 2022-05-09 10:31
Currently the build is created for the following browserslist: https://github.com/sulu/skeleton/blob/2.5/assets/admin/.browserslistrc

If you run in that directory `npx browserslist` it will show the supported browserslist:

<details><summary>Output</summary>

```
and_chr 100
and_ff 99
and_qq 10.4
and_uc 12.12
android 100
chrome 101
chrome 100
edge 100
edge 99
firefox 99
firefox 98
ios_saf 15.4
ios_saf 15.2-15.3
kaios 2.5
op_mob 64
opera 86
opera 85
safari 15.4
safari 15.2-15.3
samsung 16.0
samsung 15.0
```

</details>

Do you know which devices do not support an upgrade from IOS 13 to IOS 14?

**Comment by Adelysnet** [comment] 2022-05-09 12:05
For desktop, Mac before the following dates (if exists,  some model like iMac Pro do not have older version) : 

| Model | Year
| --- | ---
| MacBook | 2015 
| MacBook Air | mi-2012 
| MacBook Pro | mi-2012
| Mac mini | 2012
| iMac | 2012
| iMac Pro | 2017
| Mac Pro | 2013  (except those compatible with metal graphic card) 

For iPhones 

| Model | Year 
| --- | ---
| iPhone 6 or older | <= 2014

**Comment by alexander-schranz** [comment] 2022-05-09 14:27
Yeah the mac desktop/laptop list, should be all what is supporting Mojave: https://support.apple.com/kb/SP777?locale=de_AT. What device are you using, or having problems upgrading to Mojave?

If you need a quickfix you could adopt the `.browserslistrc` and do a manual build. ([Building the administration interface frontend application](https://docs.sulu.io/en/2.4/cookbook/build-admin-frontend.html)).

**Comment by Adelysnet** [comment] 2022-05-09 14:35
I am using a Mac mini mid-2011, can’t migrate to Mojave, my quick fix for now is to use Chrome, not a problem for me at development stage.  I’ll try to modify the browerslistrc and rebuild.

Thanks

**Comment by alexander-schranz** [comment] 2022-05-09 14:59
Yeah I think for laptop and desktop devices there is not a big problem as they can use another modern browser. The problem is more in iOS devices where you can not use another browser engine. We need to discuss if we want to support here a bigger range of devices or not.

I'm also not sure if the browserslist is effecting the `Intl` support 🤔. I think it does only support to polyfill what `core-js` is supporting and it seems like they currently do not have yet support for it: https://github.com/zloirock/core-js/issues/839

**Comment by Adelysnet** [comment] 2022-05-10 10:12
you are right, there is no more support for Intl in core-js, but polyfill.io do support it. 
Overriding the main adminBundle view and adding the corresponding polyfill bundle to it resolves the problem. 

```
//templates/bundles/SuluAdminBundle/Admin/main.html.twig. 
...
{% block javascript %}. 
        <script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=Intl%2CIntl.getCanonicalLocales%2CIntl.RelativeTimeFormat%2CIntl.PluralRules%2CIntl.NumberFormat%2CIntl.Locale%2CIntl.ListFormat%2CIntl.DisplayNames%2CIntl.DateTimeFormat.%7EtimeZone.golden%2CIntl.DateTimeFormat.%7EtimeZone.all%2CIntl.DateTimeFormat.prototype.formatToParts%2CIntl.DateTimeFormat"></script>  
        {#- We do not preload the files because of problems with big files on http push in Chrome -#}  
        <script src="{{ asset('main.js', 'sulu_admin') }}"></script>  
{%- endblock %}  
```

**Comment by alexander-schranz** [comment] 2023-06-29 14:13
I'm closing this the usage of Safari 13 and lower is globally seen very small.

![Bildschirmfoto 2023-06-29 um 16 12 40](https://github.com/sulu/sulu/assets/1698337/cf8844e9-6505-4b29-821e-fa71cdf46954)

If somebody need to support it the workaround by @Adelysnet provided via polyfill can be used, but we will at current state not add a polyfill for this to the core.

**Closed as completed by alexander-schranz** 2023-06-29 14:13 UTC
Labels: Bug
