### ISSUE TITLE
Pages with a Page Type of "Internal Link" are being indexed by MassiveSearch

### ISSUE THREAD

**Issue by mtnorthrop** [sulu/sulu#3239] opened 2017-02-27 17:22 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5-RC
| Browser Version | Browser name and version

#### Actual Behavior

I'm getting pages with a page type of "Internal Link" in my search results, even after running `bin/websiteconsole massive:search:purge --all --force && bin/websiteconsole massive:search:reindex`

#### Expected Behavior

I'd expect that pages of the "Internal Link" page type would not appear in the search results.

**Comment by danrot** [comment] 2017-02-28 06:36
That's a duplicate of #2940, closing it therefore. Please subscribe to the other ticket in case you want to stay up to date.

**Closed by danrot** 2017-02-28 06:36 UTC
Labels: Duplicate
