### ISSUE TITLE
Postgres supported

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2240] opened 2016-04-05 08:24 UTC
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

In order to support Postgres we must address the following issues:

- [ ] List builder: `SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"c1_.translation\" must appear in the GROUP BY clause or be used in an aggregate function`
- [ ] Test order expectations (postgres does not return rows in the same order as MySQL)

Other issues as test failures: https://travis-ci.org/sulu/sulu/jobs/120617459https://travis-ci.org/sulu/sulu/jobs/120617459

**Comment by danrot** [comment] 2016-04-05 09:35
Duplicate of #2241

**Closed by danrot** 2016-04-05 09:35 UTC
