### ISSUE TITLE
Internal links: Unhelpful error when linking page to itself

### ISSUE THREAD

**Issue by TomSeldon** [sulu/sulu#2892] opened 2016-09-01 13:41 UTC
| Q | A |
| --- | --- |
| Bug? | yes? |
| New Feature? | no |
| Sulu Version | 1.3 |
| Browser Version | Chrome (though not relevant here) |
#### Actual Behaviour

Given a content editor is editing a content item that has internal links
And the content editor links the current page to itself
When the content editor tries to "Save and publish" the content item
Then the content item will not be saved
**And the content editor is shown a generic error message**
#### Expected Behaviour

Given a content editor is editing a content item that has internal links
And the content editor links the current page to itself
When the content editor tries to "Save and publish" the content item
Then the content item will not be saved
**And the content editor is shown a helpful message explaining what they've done wrong**
#### Steps to Reproduce
- Edit a page template that has an "internal links" property
- When selecting internal links, ensure the current page is selected
- Try to "Save and publish" the page
- Error is shown: **Error: Page cannot be saved**
  ![screen shot 2016-09-01 at 14 29 23](https://cloud.githubusercontent.com/assets/3420620/18169114/8b68b116-7050-11e6-8806-8d608b6a17c2.png)
- As a content editor, it's not clear what has gone wrong and so it becomes difficult to correct the reason why it has failed
- Inspecting the network request shows the actual reason why it failed (which is great in itself, but not helpful to the average user): 
  ![screen shot 2016-09-01 at 14 31 12](https://cloud.githubusercontent.com/assets/3420620/18169170/c38c256e-7050-11e6-9ad1-dbc17def3764.png)
#### Possible Solutions
- Add validation to the `internal_links` content type that checks that the page hasn't been linked to itself (which would prevent the page being saved?)
- Show the error message returned by the API to the view (not sure how that impacts things like translations, etc.)

**Comment by wachterjohannes** [comment] 2016-09-02 07:58
@TomSeldon thanks for reporting this issue. The problem is that we currently has no "generic" way to solve that! we should discuss this here /cc @danrot

**Comment by danrot** [comment] 2016-09-12 12:12
Well, actually there is a generic way to solve that. IMO that would be generating a separate `Exception` class, emitting this kind of exception, and handle the exception in the javascript component based on its code.

**Comment by danrot** [comment] 2016-09-14 09:00
Apart from that, [this PR](https://github.com/sulu/sulu/pull/2899) also removes the possibility to add a self link to the page.

**Comment by danrot** [comment] 2018-04-30 13:40
#2899 was merged in 3d3b9a965eb548e02a9f4f30f63365e28ebcafa3, and the error above can't happen as described anymore (at least not to the content manager), so I am going to close this issue.

**Closed by danrot** 2018-04-30 13:40 UTC
Labels: UX
