### ISSUE TITLE
Provide "create shadow" option when editing ghost page

### ISSUE THREAD

**Issue by mmsbrggr** [sulu/sulu#2599] opened 2016-07-14 12:30 UTC
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
| Sulu Version | 1.2.1 |
| Browser Version | - |
#### Actual Behavior

When editing a ghost page the user has the choice between creating a new empty page, or to copy the page from another locale. However often occurring use case, when dealing with country specific webspaces, is that he or she wants to create a shadow page. This option is not available.
#### Expected Behavior

When editing a ghost page, the option to create a shadow page should be available in the popped up overlay.
#### Steps to Reproduce

Double click a ghost page in the content navigation.
#### Possible Solutions

Provide a select to choose a locale from which a shadow page gets created at the position of the ghost.

**Comment by danrot** [comment] 2019-11-07 07:56
Closing this as duplicate of #1381

**Closed by danrot** 2019-11-07 07:56 UTC
Labels: Feature, UX
