### ISSUE TITLE
blocks without maxOccurs are disabled in Admin

### ISSUE THREAD

**Issue by uricanl** [sulu/sulu#3120] opened 2017-01-03 15:30 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2
| Browser Version | All

#### Actual Behavior

Block buttons have disabled style (grey and unclickable). No action appears when click the button

#### Expected Behavior

Block buttons should be blue and clickable (in order to add a new block)

#### Steps to Reproduce

Add a block content without a "maxOccurs" parameter.

#### Possible Solutions

If there is no maxOccurs filled, use "maxOccures=999" by default.

**Comment by wachterjohannes** [comment] 2017-01-09 10:27
could you please try this with https://github.com/sulu/sulu/releases/tag/1.4.3 this should be fixed there.

**Comment by danrot** [comment] 2017-01-17 12:58
@uricanl Since you are not answering I am assuming that the issue is gone with a later version. Please reopen the issue if the error still persists.

**Closed by danrot** 2017-01-17 12:58 UTC
