### ISSUE TITLE
Content-Type "smart_content" currently not working in Snippets.

### ISSUE THREAD

**Issue by dominikmatt** [sulu/sulu#3112] opened 2016-12-21 10:38 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2

#### Actual Behavior

Sulu would like to load content from current Webspace, but snippets does not have any webspace-eky.
#### Expected Behavior

All Webspaces are selectable in Smart-Content Overlay.

#### Steps to Reproduce

Add a smart_content in some snippet and try to select a entry-point.
```
<property name="test" type="smart_content"></property>
```

#### Possible Solutions

https://github.com/sulu/sulu/blob/develop/src/Sulu/Component/Content/SmartContent/ContentDataProvider.php#L105
Change webspace-nodes param to all

**Comment by danrot** [comment] 2016-12-22 09:06
Closing, because it is a duplicate of #2939

**Closed by danrot** 2016-12-22 09:06 UTC
