### ISSUE TITLE
[Webspace] No exception when webspace node does not exist

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2342] opened 2016-04-28 07:14 UTC
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | Specific version or SHA of a commit |
| Browser Version | Browser name and version |
#### Actual Behavior

If, for some reason, the webspace node has been removed there is a Fatal Error:

```
[1] Symfony\Component\Debug\Exception\FatalErrorException: Error: Call to a member function getAllLocalizations() on null
    at n/a
        in /home/daniel/www/sulu-io/sulu/src/Sulu/Bundle/DocumentManagerBundle/Bridge/DocumentInspector.php line 279

    at Sulu\Bundle\DocumentManagerBundle\Bridge\DocumentInspector->getLocalizedUrlsForPage()
        in /home/daniel/www/sulu-io/sulu/src/Sulu/Component/Content/Compat/Structure/PageBridge.php line 35

    at Sulu\Component\Content\Compat\Structure\PageBridge->getUrls()
        in /home/daniel/www/sulu-io/sulu/src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolver.php line 65

    at Sulu\Bundle\WebsiteBundle\Resolver\StructureResolver->resolve()
        in /home/daniel/www/sulu-io/sulu/src/Sulu/Bundle/WebsiteBundle/Resolver/ParameterResolver.php line 57

    at Sulu\Bundle\WebsiteBundle\Resolver\ParameterResolver->resolve()
        in /home/daniel/www/sulu-io/sulu/src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php line 86

    at Sulu\Bundle\WebsiteBundle\Controller\WebsiteController->getAttributes()
        in /home/daniel/www/sulu-io/sulu/src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php line 53

    at Sulu\Bundle\WebsiteBundle\Controller\WebsiteController->renderStructure()
        in /home/daniel/www/sulu-io/sulu/src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php line 40

    at Sulu\Bundle\WebsiteBundle\Controller\DefaultController->indexAction()
        in /home/daniel/www/sulu-io/getzner-werkstoffe/app/bootstrap.php.cache line 3205

    at call_user_func_array:{/home/daniel/www/sulu-io/getzner-werkstoffe/app/bootstrap.php.cache:3205}()
        in /home/daniel/www/sulu-io/getzner-werkstoffe/app/bootstrap.php.cache line 3205

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
        in /home/daniel/www/sulu-io/getzner-werkstoffe/app/bootstrap.php.cache line 3167

    at Symfony\Component\HttpKernel\HttpKernel->handle()
        in /home/daniel/www/sulu-io/getzner-werkstoffe/app/bootstrap.php.cache line 3318

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle()
        in /home/daniel/www/sulu-io/getzner-werkstoffe/app/bootstrap.php.cache line 2509

    at Symfony\Component\HttpKernel\Kernel->handle()
        in /home/daniel/www/sulu-io/getzner-werkstoffe/web/website.php line 63

    at {main}()
        in /home/daniel/www/sulu-io/getzner-werkstoffe/web/website.php line 0
```
#### Expected Behavior

There should be an explicit Exception explaining the problem.

e.g.

```
Could not find webspace node `/cmf/foo` for portal `foo.xml`
```
#### Steps to Reproduce
1. Rename the `/cmf` node to `/fmc`
2. Load the website.

**Comment by kfrohwein** [comment] 2016-07-14 13:30
Hi

there problem is probably inside of the WebspaceCollection Class. To me it doesn't make sense that `null` should be an accepted return value because as far I do understand sulu.io there can't be going on if there is no webspace found.

But there are still some things to me I don't understand about sulu. Currently my fix would be like this:

  ```php
  public function getWebspace($key)
    {
        $webspace = array_key_exists($key, $this->webspaces) ? $this->webspaces[$key] : null;
        if (null === $webspace) {
            throw new \InvalidArgumentException(sprintf(
              'There was no webspace found with the key "%s"', $key
            ));
        }
        return $webspace;
    }
```
But I can't reprduce the problem. I always get a 404 error if I change the webspace name. I would expect that some of the first things sulu does is deciding which webspace to use. So how can the router component kick in before that?

**Comment by kfrohwein** [comment] 2017-02-01 23:06
I just don't understand how sulu decides which webspace to use. I know it is in the RequestAnalyser. I found how all webspaces are loaded and that the attributes the analyser checks are build in the various requestProcessors functions. So in the end it is all provided by webspacecollectionbuilder. But I just do not understand how the decision is made about the webspace key. Is it matching the portal URLs?

Plain said I can't reproduce the true reason of this bug.

**Comment by wachterjohannes** [comment] 2017-02-02 07:38
@kfrohwein yes sulu matches the portal urls with the request url. have you renamed the `/cmf` node like @dantleech mentioned?

**Comment by kfrohwein** [comment] 2017-02-17 15:15
The original issue is obsolete as sulu did change a lot since it was postet. Still there now is only a 404 error message if the webspace is not found.

The steps to reproduce by altering the PHPCR data is a real edge case that probably won't happen a lot.

Still it would be better if something other than a 404 error would be thrown.

**Comment by danrot** [comment] 2017-02-17 15:22
We decided that it is not worth the performance overhead to change this exception from a `ResourceLocatorNotFoundException` to something else. Therefore I am closing this issue.

**Closed by danrot** 2017-02-17 15:22 UTC
Labels: Bug, Easy Pick, Technical Debt
