### ISSUE TITLE
Column config is cached or user setting ?

### ISSUE THREAD

**Issue by sebheitzmann** [sulu/sulu#6162] opened 2021-07-29 14:42 UTC
| Q | A
| --- | ---
| Sulu Version | 2.2.5
| PHP Version | 7.4.6
| DB Version | Mariadb 10.4
| Browser Version | Chrome 91.0.4472.101

# Actual Behavior

I have two different admin user which doesn't see the same column in the column config list.

![image](https://user-images.githubusercontent.com/2197902/127511704-895fce1b-cf76-4268-ae76-9852725a8eea.png)

The last column is not present on the same admin, same navigator but for another user ( same right ). And on a newly created user.

![image](https://user-images.githubusercontent.com/2197902/127511978-45d591dd-053e-4766-8161-0b15c8cac48b.png)

# Expected Behavior

See the same column for all admin user

# Steps to Reproduce

Good question ...

# Possible Solutions

I suspected the browser cache, but it's not the case. I suspected a Proxy cache but in my office i can reproduce the same problem. I suspected that the user is storing some cache data so i created a new user but the same problem persist.

Sorry to post this problem without a solution ...

**Comment by sebheitzmann** [comment] 2021-07-29 14:43
The columns order are not the same on the two screenshot but i don't have the same number of column.

**Comment by alexander-schranz** [comment] 2021-07-29 15:27
Looks for me like that they are cached in the `se_user_settings` table. The `se_user_settings` saves the last selected items, selected columns, filters, views. To fix your problem you could truncate that table or just remove the specific setting key for your user which does not list all column list.

**Comment by sebheitzmann** [comment] 2021-07-30 05:02
![image](https://user-images.githubusercontent.com/2197902/127602754-32610095-5f45-4acd-b57e-fac01a0fdf55.png)

this info are cached in the table. But I don't really understand why ? If i add a new column in the adherent.xml file it will not be changed for old user ?

**Comment by alexander-schranz** [comment] 2021-07-30 08:39
@sebheitzmann  the settings should be merged with exist columns but looks like currently they are overwritten with the user columns. Not sure if it was fixed in some version after the one you are using. If not I think the problem is somewhere in this method https://github.com/sulu/sulu/blob/0238c55bd6a4d965aa7ebd12b2ba7467f33db957/src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js#L289-L313 that the columns get lost.

**Comment by niklasnatter** [comment] 2021-08-02 12:15
I think this problem should be fixed in https://github.com/sulu/sulu/pull/5267. Is it possible that your project uses an outdated admin javascript build? 
Make sure to update the admin javascript build in you project when upgrading your project like described in the [upgrade guide in the documentation](https://docs.sulu.io/en/2.2/upgrades/upgrade-2.x.html) 🙂

**Comment by niklasnatter** [comment] 2021-08-10 12:41
Closing this because of inactivity. Please feel free to create a new issue if the problem persists for you after updating the admin javascript build 🙂

**Closed as completed by niklasnatter** 2021-08-10 12:41 UTC
Labels: Bug

**Comment by sebheitzmann** [comment] 2021-08-11 07:03
I'm sorry, I was in holidays for two weeks. I've found a workaround for the moment and I have seen that the new version should correct the pb. I will try that. Thanks for all.
