### ISSUE TITLE
API Documentation 

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2839] opened 2016-08-19 12:15 UTC
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes

#### Actual Behavior

No api documentation for sulu.

#### Expected Behavior

Maybe include of following bundle in admin kernel for the rest api documentation https://github.com/nelmio/NelmioApiDocBundle

**Comment by danrot** [comment] 2016-08-19 14:16
Duplicate of https://github.com/sulu/sulu/issues/1715

**Closed by danrot** 2016-08-19 14:16 UTC
