### ISSUE TITLE
Is there any way to tweak the column width in the admin panel to avoid the ellipsis in the title?

### ISSUE THREAD

**Issue by dalailomo** [sulu/sulu#3319] opened 2017-04-20 13:06 UTC
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.4.0
| Browser Version | -

#### Actual Behavior

In pages with long titles, an ellipsis appears in the middle of the title, making it hard to read in some situations.

![screen shot 2017-04-20 at 14 06 10](https://cloud.githubusercontent.com/assets/6674841/25232259/933dd870-25d2-11e7-8409-26383b593915.png)

#### Expected Behavior (?)

Is there any way to tweak the column width values? Thanks!

**Comment by wachterjohannes** [comment] 2017-04-20 13:47
@dalailomo TBH currently not. there is a constant in our javascript library which cannot be overwritten from outside. @berndhep what do you think would that be a good idea to make that configurable?

**Comment by dalailomo** [comment] 2017-05-03 12:31
@wachterjohannes thanks for the response.

Honestly it would be a very nice feature :)

**Comment by danrot** [comment] 2019-07-26 06:07
This is a duplicate of #3286

**Closed by danrot** 2019-07-26 06:07 UTC
Labels: Enhancement
