### ISSUE TITLE
Permissions are displayed wrong for new user role in tab

### ISSUE THREAD

**Issue by thomasduenser** [sulu/sulu#3083] opened 2016-12-13 10:04 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.2

#### Actual Behavior

When having multiple user roles, everything work's fine after creating a new page. Then it looks something like this in the permissions tab:

![bildschirmfoto 2016-12-13 um 11 01 56](https://cloud.githubusercontent.com/assets/3875917/21135890/9a080680-c123-11e6-9464-3a761bec311c.png)

After adding a new user role, there's no entry in the database table `se_access_control` for each existing page and in the permission tabs it is visualized like this:

![bildschirmfoto 2016-12-13 um 10 53 48](https://cloud.githubusercontent.com/assets/3875917/21135908/aa08e978-c123-11e6-9a02-147e09f0b647.png)

Looks wrong, as there's no permission set. Seems like it's displaying (but not using) the default permissions set for this role.

#### Expected Behavior

Newly created user roles shouldn't see pages after the role have been created.

#### Steps to Reproduce

1. Create multiple user roles
2. Create a page with user role 1
3. Check permissions in the tab with user role 1 -> looks good (1 has permissions, all others doesn't)
4. Create a new user role
5. Check permissions in the tab again with user role 1 -> looks wrong, as the newly created user role seems to have the permissions

**Comment by danrot** [comment] 2016-12-16 10:23
@thomasduenser Just to get this clear: The information shown is correct, right? So the permissions you see here are also applied the same way. We just don't want that a new role gets all the object-specific permissions from the very beginning?

**Comment by thomasduenser** [comment] 2016-12-16 10:25
@danrot Correct. The permissions of the role are the four green ones (view, add, edit, delete) as visualized.

**Comment by danrot** [comment] 2019-11-21 12:21
Can't reproduce anymore, therefore closing it.

**Closed by danrot** 2019-11-21 12:21 UTC
Labels: Bug
