### ISSUE TITLE
Allow to copy and move pages between webspaces

### ISSUE THREAD

**Issue by plozmun** [sulu/sulu#5347] opened 2020-06-15 08:25 UTC
# Problem description

In a multi market website the content usually is similar but not the same. Now an editor cannot create a page and copy it from UI to another webspace to not repeat work.

# Proposed solution

Allow to copy or move pages ( and subpages ) from one webspace to another if user has right permissions.

**Comment by alexander-schranz** [comment] 2020-06-16 08:54
Copy a page from one to another Webspace I see not as a Problem, if the target webspace does not have that template they should get a message and would need then to switch the template after copying, which would be the same screen they should get when a dev removed a template and the page still exists in that template.

Moving I see more as problem as I'm not sure if the Url History would work this way and could get very complicated.

**Comment by danrot** [comment] 2020-06-18 06:23
AFAIK the screen you are talking about has never existed. I can only remember that we have shown the page as striked through in the column list, and you haven't been able to open it then anymore. The only available to get rid of that was to delete that page.

But I can totally see that content managers want that feature. So I am going to add "Needs more information" label, since we need to think about handling that from a UX part.

And regarding moving: The only sensible thing to do IMO is to be able to span the URL history over multiple webspaces. That might not be easy to implement, but everything else might confuse users, and has very high potential to corrupt the website's search engine ranking.

**Comment by danrot** [comment] 2020-06-18 06:29
Actually I am going to close it, because it is a duplicate of #4502 :see_no_evil:

**Closed by danrot** 2020-06-18 06:29 UTC
Labels: Feature, Needs Information
