### ISSUE TITLE
Sorting pages not working

### ISSUE THREAD

**Issue by rogoit** [sulu/sulu#4396] opened 2019-01-28 16:14 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | actual dev
| Browser Version | Chrome 71

#### Actual Behavior

When i try to change a number error popup comes

#### Expected Behavior

That i can sort pages

#### Steps to Reproduce

In page tree the order button

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)
![bildschirmfoto von 2019-01-28 17-09-59](https://user-images.githubusercontent.com/3101439/51849474-1af99280-2320-11e9-9b92-d5bef3a8ebb9.png)
![bildschirmfoto von 2019-01-28 17-10-20](https://user-images.githubusercontent.com/3101439/51849475-1af99280-2320-11e9-8696-58dcfb4bea79.png)

**Comment by danrot** [comment] 2019-01-30 06:52
That's not an error popup, that's just a dialog to ask if you are sure what you are doing (similar to what you see when you are trying to delete something). I've just tested it, after clicking the OK button it works. Have you tried that? If yes, what errors do you get after clicking the OK button?

**Comment by danrot** [comment] 2019-01-31 14:46
I just tried again, and can only say that it works. If you don't pass any additional information on how to reproduce the error I am afraid I can't do anything and have to close this issue. These are my steps to reproduce: 

1. Navigate to http://127.0.0.1:8000/admin/#/webspaces/example/en (assuming your webspace is called example)
2. Hover the column in which I want to to order the pages and click the settings icon
3. Click on "Order" in the settings menu
4. Write "2" instead of "1" in the first text line appearing
5. Click outside the text line to make it lose its focus
6. Confirm the overlay you have posted above by clicking "Ok"
7. After a short loader in the "Ok" button the pages are reordered in their column

**Comment by rogoit** [comment] 2019-01-31 14:50
Later i hope i can check...thx so far my friend

**Comment by danrot** [comment] 2019-02-26 07:53
Since the error does not seem to be reproduceable I am going to close this issue.

**Closed by danrot** 2019-02-26 07:53 UTC
Labels: Needs Information

**Comment by rogoit** [comment] 2019-02-26 08:23
Ok now works for me...sorry for missing response my friend!!
