### ISSUE TITLE
CSS problems with media_selection property in highlight section 

### ISSUE THREAD

**Issue by reflexxion** [sulu/sulu#3103] opened 2016-12-19 14:57 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3, 1.4

#### Actual Behavior

Using a `media_selection` property inside of a templates "highlight section" there are some displaying issues.

Inside highlight section:
![inside_highlight](https://cloud.githubusercontent.com/assets/3419968/21317041/c1182932-c603-11e6-821c-2f0411e9d9b6.png)

Outside highlight section:
![inside_own](https://cloud.githubusercontent.com/assets/3419968/21317040/c117f5b6-c603-11e6-919c-0abea890fb9f.png)

**Comment by danrot** [comment] 2016-12-19 15:02
@berndhep What should we do about this?

**Comment by danrot** [comment] 2017-08-01 12:55
Closing as duplicate of #3456. This is issue is older, but the other contains more details.

**Closed by danrot** 2017-08-01 12:55 UTC
Labels: Bug
