### ISSUE TITLE
Search indexing of Shadow Pages doesn't work

### ISSUE THREAD

**Issue by thomasduenser** [sulu/sulu#3427] opened 2017-06-30 09:15 UTC
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Tested in 1.2 and 1.6

#### Actual Behavior

Our project uses the default website search and we have multiple locales. After purging (`app/webconsole massive:search:purge --all`) and reindexing (`app/webconsole massive:search:reindex -e prod`) the search show's only *normal* pages which aren't shadow pages.

#### Expected Behavior

The search should also return the pages that are shadows.

#### Steps to Reproduce

1. Create a webspace with following localizations and the a URL configuration like  
`<url>{host}/{localization}</url>`:  

```yml
<localizations>
    <localization language="de" default="true">
        <localization language="de" country="at"/>
    </localization>
</localizations>
```

2. Create a page in `de` called `Test`
3. Create a page in `de_at` called `Test` and save it as shadow (source `de`)
4. Use the website search in `de` and search for `Test` ✅ 
5. Use the website search in `de_at` and search for `Test` ✅ 
6. Purge the search and reindex again (*commands are some lines above*)
7. Use the website search in `de` and search for `Test` ✅ 
8. Use the website search in `de_at` and search for `Test` ❌ 

#### Possible Solutions

I think that the reindex command doesn't handle shadow pages correct. At the time of saving it is correct, so maybe only the command needs a bugfix.

**Comment by danrot** [comment] 2017-07-18 15:59
Is it possible that this is also not working when not using the `reindex` command? Have you tried using another name than `Test` in step 3? For me the page can only be found by the original (non-shadow) title...

**Comment by thomasduenser** [comment] 2017-07-19 06:25
@danrot I've tested it again with Sulu 1.6.1 and in step 3 I've named it `Test AT`. When searching in that language (`de-at`)  for `test` or `test en` I get the correct result.

**Comment by wachterjohannes** [comment] 2017-07-31 05:25
@danrot @thomasduenser the linked PR is merged? can we also close this issue?

**Comment by danrot** [comment] 2017-07-31 06:04
No, we can't, because of the reasons I've explained in the other PR. It's still not working correctly for every case.

**Comment by danrot** [comment] 2019-11-27 07:24
Just tried to reproduce, seems to be fixed :+1:

**Closed by danrot** 2019-11-27 07:24 UTC
