### ISSUE TITLE
Smart content template filter

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3418] opened 2017-06-26 11:14 UTC
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.6
| Browser Version | --

#### Actual Behavior

At the moment smart content cant filter by template keys.

#### Expected Behavior

Maybe a filter by templates would be nice.

**Comment by danrot** [comment] 2019-11-21 16:07
Duplicate of #1456

**Closed by danrot** 2019-11-21 16:07 UTC
