### ISSUE TITLE
Rendering json encoded sulu-link tag in template leads to endless loop

### ISSUE THREAD

**Issue by Prokyonn** [sulu/sulu#6243] opened 2021-09-23 06:41 UTC
| Q | A
| --- | ---
| Sulu Version | >1.6.x and >2.x

# Actual Behavior

Trying to resolve an json encoded `sulu:link` (1.6) or `sulu-link` (2.x) results in an endless loop. 

The recursive method `parse` of the `HtmlMarkupParser` is infinitely called, because the regex 
for the `tagExtractor->count(..)` method just searches for `sulu-link` and finds the encoded entry, but the regex of `tagExtractor->extract(..)` doesn't match anything, because of the encoding.

# Expected Behavior

No endless loop. Either resolve the link or just ignore it because it is encoded.

# Steps to Reproduce

Json encode the text-editor content with a  `sulu-link` in twig and request the template.

# Possible Solutions

Adjust the [count](https://github.com/sulu/sulu/blob/2.x/src/Sulu/Bundle/MarkupBundle/Markup/HtmlTagExtractor.php#L19) and/or the [tag](https://github.com/sulu/sulu/blob/2.x/src/Sulu/Bundle/MarkupBundle/Markup/HtmlTagExtractor.php#L23) regex.

**Comment by mamazu** [comment] 2024-06-15 15:55
Closed as duplicate of #6965

**Closed as completed by mamazu** 2024-06-15 15:55 UTC
Labels: Bug
