### ISSUE TITLE
External links and shadow pages should have resource_locator field in settings tab

### ISSUE THREAD

**Issue by luca-rath** [sulu/sulu#6686] opened 2022-07-07 12:00 UTC
# Problem description

Currently it's hard for the content manager to change the route path of a page of type external link or of a shadow page.

The necessary steps are:
- Change page type to `Content` or disable shadow page
- Change route path in `Details` tab
- Change page type back to `External link` or enable shadow page again

# Proposed solution

Add `resource_locator` property to `Settings` tab

**Comment by alexander-schranz** [comment] 2022-07-07 13:27
Why I'm first a little bit not happy about External Page (as it should not have internal url). It make sense when it is a parent page. For all cases "Internal", "External", "Shadow", it make sense that I can remove history urls. So yeah the easiest way is `title` and `url` (including removing history urls) is always able to be changed.

**Comment by niklasnatter** [comment] 2022-07-11 12:22
I think this is related to (or a duplicate of?) https://github.com/sulu/sulu/issues/2314.

**Comment by alexander-schranz** [comment] 2022-07-11 12:31
Yes it is the same. We should add the information to the other issue.

**Closed as completed** 2022-07-11 12:31 UTC
Labels: Feature
