### ISSUE TITLE
Switch language in preview mode

### ISSUE THREAD

**Issue by ThiKool** [sulu/sulu#5136] opened 2020-03-25 09:20 UTC
# Actual Behavior

If I switch the language from de to en at the admin panel editor nothing happen in the review window. The reload button has also no effect. The only work arround is that I clear the cache (bin/adminconsole c:c) after I've switched the language.

![image](https://user-images.githubusercontent.com/32712471/77521102-740c7a00-6e82-11ea-948d-11ecd205c358.png)
the dump is "app.request"

**Comment by danrot** [comment] 2020-03-27 08:33
Duplicate of #5084

**Closed by danrot** 2020-03-27 08:33 UTC
Labels: Bug
