### ISSUE TITLE
DoctrineFieldDescriptor named `from` Problem

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2307] opened 2016-04-17 20:11 UTC
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.1.4 |
#### Actual Behavior

Field named `from` dont work in FieldDescriptors in `cgetAction` when Entry exists.
The error return the next element in my case `to` but if I will remove `to` it will error on the nextelement. It works when I remove the `from` FieldDescriptor.

```
[Semantical Error] line 0, col 247 near ', My\\Bundle\\EventBundle\\Entity\\Event.to': Error: Class ',' is not defined.
```
#### Expected Behavior

cgetAction should work without a problem.
#### Steps to Reproduce
1. Create a entity with a field `from`

``` xml
        <field name="from" column="fromDateTime" type="datetime" />
```
1. Add a the field to the FieldDescriptor

``` php
        $fieldDescriptors['from'] = new DoctrineFieldDescriptor(
            'from',
            'from',
            Event::class,
            'my_event.from',
            [],
            false,
            false,
            'date'
        );
```
1. Save a entity that the list is not empty
2. Now the error appears on the cgetAction on flat=true
#### Possible Solutions

It works when the `AS` alias is removed from https://github.com/sulu/sulu/blob/1.2.0/src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php#L141. So a possible solution would be only add the `AS` when `getName` is not equal to `getFieldName` but `getFieldName` seems not exists everytime.

**Comment by danrot** [comment] 2016-09-20 07:25
This is actually quite a tricky one... I thought we could simply use backticks to escape all these aliases, but this doesn't work because DQL doesn't support that. An idea would be to introduce our own user defined DQL function which escapes these names, but the problem is that mysql uses backticks whereby other database systems don't.

**Comment by danrot** [comment] 2017-02-22 15:21
Closing, since this is a doctrine issue, and we don't want to maintain a separate user defined DQL function...

**Closed by danrot** 2017-02-22 15:21 UTC
Labels: Bug
