### ISSUE TITLE
CKEditor styles underneath dropdown inside block

### ISSUE THREAD

**Issue by cirykpopeye** [sulu/sulu#5375] opened 2020-06-30 12:00 UTC
| Q | A
| --- | ---
| Sulu Version | 2.1
| Browser Version | Chrome 83.0.4103.106
# Actual Behavior

Styles get shifted underneath the dropdown below

# Expected Behavior

That the styles get presented above the dropdown, making it possible to select the styles on the bottom

# Steps to Reproduce

Add more styles to the ckeditor, prevent having to much text and add a dropdown below it

# Possible Solutions

```
.ck.ck-editor {
    z-index: 1;
}
```

instead of

```
.ck.ck-editor {
    z-index: 0;
}
```

![Schermafbeelding 2020-06-30 om 13 56 03](https://user-images.githubusercontent.com/17956647/86127589-7107d200-bae0-11ea-878f-de358ab06213.png)

**Comment by cirykpopeye** [comment] 2020-06-30 12:38
If above solution is applied, than the ckeditor is above backdrop when opening smart content filter f.e., so than that needs a z-index: 1; and in turn the overlay also z-index: 1.

**Comment by alexander-schranz** [comment] 2020-06-30 12:41
@cirykpopeye Can you show a screenshot or better a screencast, I can not reproduce it or I'm not sure which dropdown you are talking about.

**Comment by cirykpopeye** [comment] 2020-06-30 12:46
> @cirykpopeye Can you show a screenshot or better a screencast, I can not reproduce it or I'm not sure which dropdown you are talking about.

I already made the screenshot, but forgot to add it. Issue updated :)

**Comment by cirykpopeye** [comment] 2020-06-30 12:53
Updating the index to 0 though gives lots of other issues. (The ones mentioned above and also the dropdowns above a ckeditor are now shown below it. 

![Schermafbeelding 2020-06-30 om 14 53 10](https://user-images.githubusercontent.com/17956647/86128251-70237000-bae1-11ea-85ad-1767b34f4537.png)

**Comment by alexander-schranz** [comment] 2020-06-30 13:08
@cirykpopeye can you give #5379 a try?

**Comment by cirykpopeye** [comment] 2020-06-30 13:25
> @cirykpopeye can you give #5379 a try?

![Schermafbeelding 2020-06-30 om 15 23 34](https://user-images.githubusercontent.com/17956647/86131263-b5e23780-bae5-11ea-9d89-5f006786efe0.png)

I have a similar issue. Though now removing transform: translateX(0) fixes it for me.

![Schermafbeelding 2020-06-30 om 15 24 47](https://user-images.githubusercontent.com/17956647/86131356-dc07d780-bae5-11ea-9f03-d439ce8e577d.png)

**Comment by cirykpopeye** [comment] 2020-06-30 13:34
![Schermafbeelding 2020-06-30 om 15 33 40](https://user-images.githubusercontent.com/17956647/86132391-19b93000-bae7-11ea-95b5-dbca9c12f67c.png)

Although that now the arrow of the style in the ckeditor is present inside the dropdown of the above selection

**Comment by nnatter** [comment] 2020-06-30 15:45
@cirykpopeye Could you test https://github.com/sulu/sulu/pull/5379/files on your system again? 🙂

**Comment by cirykpopeye** [comment] 2020-07-01 09:23
> @cirykpopeye Could you test #5379 on your system again? 🙂

![Schermafbeelding 2020-07-01 om 11 21 00](https://user-images.githubusercontent.com/17956647/86227414-44f65a80-bb8d-11ea-8938-83a407ad39c9.png)

No :( Are you not having the same issue?

**Comment by nnatter** [comment] 2020-07-07 11:14
Yes, I think this is happening on most browsers at the moment 😕  Unfortunately, I dont know how to properly fix this at the moment. Hopefully @danrot has some idea.

**Comment by danrot** [comment] 2020-07-16 09:09
Hm, not at the moment... The problem with z-indexes is that they always break something...

Just adding more information here: This is probably broken since #5138. This removed almost all `z-index` values, because they were making troubles in other areas (namely the filter components in the list introduced in #5035 were not working correctly, since the `Backdrop` component was in the way of some click areas).

As you can see in #5138 some of the ckeditor elements were "shining" through e.g. `Overlay` and `Dialog` components, this is why one of the very few (maybe only) `z-index` value was set on the ckeditor with a value of 0, to avoid that kind of behavior. However, that causes the bug you have just reported.

What strikes me as odd, is that the dropzone is only below the text field, but not below the text fields label. I don't have time to have a closer look at that right now, but that might be a clue worth investigating.

**Comment by alexander-schranz** [comment] 2020-12-23 11:25
This was also reported in the slack channel:

![dropdown-behind-fields](https://user-images.githubusercontent.com/1698337/102991581-c5cd5800-4519-11eb-9c40-bc41f009c710.png)

Here we have a strange behaviour also with the "Add Button" of the Selection.

**Comment by niklasnatter** [comment] 2021-01-12 14:05
Thanks for reporting! This should finally be fixed in the next release by https://github.com/sulu/sulu/pull/5744 🎉

**Closed by niklasnatter** 2021-01-12 14:05 UTC
Labels: Bug, UX
