### ISSUE TITLE
Add order option in smart content sorting

### ISSUE THREAD

**Issue by GillesKnockaert** [sulu/sulu#5017] opened 2020-01-29 15:04 UTC
# Problem description

I have a set of pages that are sorted in a specific way, now i need the top 3 items displayed on the homepage. I would like to use smart content for this but in the sort by dropdown you have no option that takes your sorting into account.

![sort-by](https://user-images.githubusercontent.com/7395323/73368188-db59e380-42b0-11ea-9c6d-98b197b2bb81.png)

# Proposed solution

It would be nice to have an option called order so that when selecting this it maintains the order you made. if i would then select order en limit my results to 3 items. i would get the top 3 items.

**Comment by danrot** [comment] 2020-01-29 16:04
This is something we wanted to already add some time ago, but haven't found the time to do it... The problem is as described in sulu/sulu-standard#840 that it is not that easy decide how to order when sub pages are also included. On solution we have already talked about, was that we want to hide this option when include sub pages is checked. I am going to have another look at this soonish.

**Comment by danrot** [comment] 2020-02-10 12:24
Fixed in #5022

**Closed by danrot** 2020-02-10 12:24 UTC
Labels: Feature
