### ISSUE TITLE
Error when building admin with custom JS: TypeError: (void 0) is not a function

### ISSUE THREAD

**Issue by ymc-thzi** [sulu/sulu#5853] opened 2021-03-01 16:47 UTC
| Q | A
| --- | ---
| Sulu Version | 2.2.4

# Actual Behavior
I have added some custom buttons and stuff to the admin js. (../sulu/assets/admin/index.js). I have built this with 
`$ bin/console sulu:admin:update-build`
and answered the commands questions with NO, don't overwrite my custum script and then YES create a build now. It worked very well for months now.
Now when the custom admin js is built (even without any changes) I got JS errors in the console in Sulu as soon as I select a list or any content.
Maybe there are some node dependencies that has changed. I have no idea where this comes from 🤷🏻‍♂️ 
The error occurs in a script part named "mobx-react v5.4.4"

![Bildschirmfoto 2021-03-01 um 17 44 56](https://user-images.githubusercontent.com/1804472/109529314-e71c6880-7ab5-11eb-9262-e11180e82390.png)

# Expected Behavior

Custom Admin JS builds runs Sulu without errors

# Steps to Reproduce

`$ echo "n y" | bin/console sulu:admin:update-build`

**Comment by alexander-schranz** [comment] 2021-03-01 17:41
@ymc-thzi Can you show our `package.json` you should have no greater or lower version of a dependency in it which is in the skeleton for your version. E.g. [2.2.4](https://github.com/sulu/skeleton/blob/2.2.4/assets/admin/package.json).

I can not reproduce it without knowing what you did change in your assets/admin folder because without changes `bin/console sulu:admin:update-build` will always download the build.

Best would be if you could give us a step by step tutorial or a test repository where it happens:

Example I did the following but could not reproduce your error:

```bash
composer create-project sulu/skeleton
cd skeleton
echo 'DATABASE_URL=mysql://root:@127.0.0.1:3306/sulu_tmp?serverVersion' >> .env.local
```

```bash
bin/console sulu:build dev --destroy
```

Changing the `assets/admin/package.json` `"name"` parameter:

```bash
bin/console sulu:admin:update-build # answered with no for update files and yes for creating a manual build
```

```
php -S 127.0.0.1:8000 -t public config/router.php
```

Then I visited [127.0.0.1:8000/admin/](127.0.0.1:8000/admin/) and I could login without any JS error. I test it with `Node: v12.21.0` and `Node v14.16.0`.

**Comment by ymc-thzi** [comment] 2021-03-02 08:30
@alexander-schranz thanks for the answer.

- The package.json seems unchanged. (If I change i.e. a version number the update-build command asks me to overwrite or merge it, but I have kept the original)
- If I make a change with nothing functional like a space or a comment to ../sulu/assets/admin/index.js only to force the update-build command to ask me to build the admin and not to download it. Then the js contains the error.

Steps to reproduce:

1. Setup a Sulu
2. Change something like adding a comment to ../sulu/assets/admin/index.js 
3. `$ bin/console sulu:admin:update-build` => 
(Answer NO:) Do you want to overwrite your local version of "index.js"? [y]: n
(Answer YES:)  Do you want to create a build now? [y]: y
4. Login to Sulu Admin in browser and navigate to webspaces or something else => blank page/JS Error

package.json:

```json
{
    "name": "sulu-skeleton",
    "license": "MIT",
    "repository": "https://github.com/sulu/skeleton.git",
    "scripts": {
        "preinstall": "node ../../vendor/sulu/sulu/preinstall.js",
        "build": "webpack --mode production",
        "watch": "webpack --mode development -w"
    },
    "dependencies": {
        "mobx": "^4.0.0",
        "mobx-react": "^5.0.0",
        "react": "^16.2.0",
        "react-dom": "^16.2.0",
        "sulu-admin-bundle": "file:../../vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Resources/js",
        "sulu-audience-targeting-bundle": "file:../../vendor/sulu/sulu/src/Sulu/Bundle/AudienceTargetingBundle/Resources/js",
        "sulu-category-bundle": "file:../../vendor/sulu/sulu/src/Sulu/Bundle/CategoryBundle/Resources/js",
        "sulu-contact-bundle": "file:../../vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Resources/js",
        "sulu-custom-url-bundle": "file:../../vendor/sulu/sulu/src/Sulu/Bundle/CustomUrlBundle/Resources/js",
        "sulu-location-bundle": "file:../../vendor/sulu/sulu/src/Sulu/Bundle/LocationBundle/Resources/js",
        "sulu-media-bundle": "file:../../vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Resources/js",
        "sulu-page-bundle": "file:../../vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Resources/js",
        "sulu-preview-bundle": "file:../../vendor/sulu/sulu/src/Sulu/Bundle/PreviewBundle/Resources/js",
        "sulu-route-bundle": "file:../../vendor/sulu/sulu/src/Sulu/Bundle/RouteBundle/Resources/js",
        "sulu-search-bundle": "file:../../vendor/sulu/sulu/src/Sulu/Bundle/SearchBundle/Resources/js",
        "sulu-security-bundle": "file:../../vendor/sulu/sulu/src/Sulu/Bundle/SecurityBundle/Resources/js",
        "sulu-snippet-bundle": "file:../../vendor/sulu/sulu/src/Sulu/Bundle/SnippetBundle/Resources/js",
        "sulu-website-bundle": "file:../../vendor/sulu/sulu/src/Sulu/Bundle/WebsiteBundle/Resources/js"
    },
    "devDependencies": {
        "@babel/core": "^7.5.5",
        "@babel/plugin-proposal-class-properties": "^7.5.5",
        "@babel/plugin-proposal-decorators": "^7.4.4",
        "@babel/plugin-proposal-object-rest-spread": "^7.5.5",
        "@babel/plugin-transform-flow-strip-types": "^7.4.4",
        "@babel/preset-env": "^7.5.5",
        "@babel/preset-react": "^7.0.0",
        "@ckeditor/ckeditor5-dev-utils": "^23.5.1",
        "@ckeditor/ckeditor5-theme-lark": "^23.0.0",
        "autoprefixer": "^9.6.1",
        "babel-loader": "^8.0.6",
        "clean-webpack-plugin": "^3.0.0",
        "css-loader": "^3.2.0",
        "file-loader": "^6.0.0",
        "glob": "^7.1.2",
        "mini-css-extract-plugin": "^0.9.0",
        "optimize-css-assets-webpack-plugin": "^5.0.3",
        "postcss-calc": "^7.0.1",
        "postcss-hexrgba": "^2.0.0",
        "postcss-import": "^12.0.1",
        "postcss-loader": "^3.0.0",
        "postcss-nested": "^4.1.2",
        "postcss-simple-vars": "^5.0.2",
        "raw-loader": "^4.0.0",
        "regenerator-runtime": "^0.13.3",
        "webpack": "^4.20.2",
        "webpack-clean-obsolete-chunks": "^0.4.0",
        "webpack-cli": "^3.1.1",
        "webpack-manifest-plugin": "^2.0.2"
    }
}
```

**Comment by alexander-schranz** [comment] 2021-03-02 09:16
@ymc-thzi Which version of node and npm are you using to create the build?

**Comment by niklasnatter** [comment] 2021-03-02 09:20
I just set up a clean project using the `sulu/skeleton` and cannot reproduce the problem with the following environment:
```
▶ node -v
v12.17.0

▶ npm -v              
6.14.11
```

What versions are you using? Have you tried updating your Node.js/npm version?

**Comment by ymc-thzi** [comment] 2021-03-02 09:36
node: v10.23.2
npm: 6.14.10

I will give it a try updating node...

**Comment by niklasnatter** [comment] 2021-03-02 15:06
Node 10 will reach its end of life quite soon (April 2021), I could imagine that there are packages in the dependency tree that already dropped support for it. Can you try to update to Node 12 or Node 14?

**Comment by ymc-thzi** [comment] 2021-03-02 17:27
Still the same after upgrading node to v14.16.0 🤷🏻‍♂️

**Comment by niklasnatter** [comment] 2021-03-03 10:08
I spent some additional time on this today, but I am still not able to reproduce the problem on `Sulu 2.2.5`, I am sorry.
To rule out system specific settings on my machine I created the build inside different versions of the official [`node` docker image](https://hub.docker.com/_/node). 

Note that the `node` container cannot execute PHP code and therefore cannot execute the `sulu:admin:update-build` command. But we can just execute the commands that would be executed by the [`UpdateBuildCommand ::doManualBuild` method](https://github.com/sulu/sulu/blob/2.x/src/Sulu/Bundle/AdminBundle/Command/UpdateBuildCommand.php#L249-L275) manually like this:

1. Start a `node` container with the desired version and map the the current directory into the `/var/project` folder in the container

```bash
docker run --rm --interactive --tty --volume ${PWD}:/var/project node:14.16.0 /bin/bash

# for completion: using another node version is possible by adjusting the tag of the node image
# docker run --rm --interactive --tty --volume ${PWD}:/var/project node:10.24.0 /bin/bash
# docker run --rm --interactive --tty --volume ${PWD}:/var/project node:12.21.0 /bin/bash
```

2. Cleanup previously created node_modules folders and package-lock.json files

```bash
cd /var/project
rm -rf assets/admin/node_modules && rm -rf vendor/sulu/sulu/node_modules && rm -rf vendor/sulu/sulu/src/Sulu/Bundle/*/Resources/js/node_modules
rm -rf assets/admin/package-lock.json && rm -rf vendor/sulu/sulu/package-lock.json && rm -rf vendor/sulu/sulu/src/Sulu/Bundle/*/Resources/js/package-lock.json
```

3. Create the administration interface build

```bash
cd /var/project/assets/admin
npm install
npm run build
```

I tested these steps with the following tags of the `node` image without encountering a problem when testing the generated build:

- `node:10.24.0`
- `node:12.21.0`
- `node:14.16.0`

Can you try if this process works on your system too?

**Comment by ymc-thzi** [comment] 2021-03-03 11:03
@nnatter thanks for you effort. Unfortunately the manual build still creates a js that is different than the one Sulu is providing when downloading it. This is the output of  `npm run build`. I can't find anything suspicious...

EDIT: removed the output because it does not contain any relevant information

**Comment by niklasnatter** [comment] 2021-03-03 11:18
> Unfortunately the manual build still creates a js that is different than the one Sulu is providing when downloading it.

What do you mean with this? There are a lot of factors that affect the generated build (eg. system specific paths, see https://github.com/webpack/webpack/issues/7179). So it is expected that the build generated on your system slightly differs from the build included in the release.

**Comment by ymc-thzi** [comment] 2021-03-03 13:36
Sorry for the misleading wording. I mean different so that it throws errors and crashes the Admin...
I am still searching...

**Comment by alexander-schranz** [comment] 2021-03-03 13:48
@ymc-thzi Can you try to update to `2.2.5` sulu version and check if it works there for you?

**Comment by ymc-thzi** [comment] 2021-03-03 13:54
@alexander-schranz I tried that already. But there were so many dependencies problems so I gave up. This Symfony satisfiable bla bla that some other bundles could not be updated
gedmo/doctrine-extensions:3.0.3
stof/doctrine-extensions-bundle:1.5.0
antishov/doctrine-extensions-bundle:1.4.3
and so on, it does not stop to complain 😖

**Comment by alexander-schranz** [comment] 2021-03-03 13:57
you can only update a specific dependency with:

```
composer update sulu/sulu
```

to update sulu only to 2.2.5

**Comment by niklasnatter** [comment] 2021-03-03 14:00
@ymc-thzi I only tested this with `Sulu 2.2.5` until now. I can finally reproduce the problem with `Sulu 2.2.4` 🎉  For completion, this is the error in the development console of the browser:
```
TypeError: (void 0) is not a function
    at core.js:84
    at r (index.js:50)
    at $n (formatters.js:165)
    at e.formatToParts (core.js:123)
    at e.format (core.js:101)
    at er (Translator.js:26)
    at e.render (List.js:645)
    at Pe (mobx.module.js:1015)
    at index.module.js:847
    at me (mobx.module.js:801)
```

It looks like this is a bug caused by conflicting versions of the `tslib` package in our dependency tree. **The problem should be fixed by #5827 in Sulu 2.2.5.**

**Comment by ymc-thzi** [comment] 2021-03-03 14:04
YAY... thats good news, I will check 2.2.5

**Comment by ymc-thzi** [comment] 2021-03-03 14:45
Oh man... this is so hard 😨 
composer update sulu/sulu doesn't do anything

![Bildschirmfoto 2021-03-03 um 15 44 31](https://user-images.githubusercontent.com/1804472/109822758-90d73300-7c37-11eb-9d6d-ab6734f5d852.png)

**Comment by ymc-thzi** [comment] 2021-03-03 15:50
But finally I made it 🎉. Confirmed 2.2.5 works again with custom admin builds.
Thanks guys...

**Comment by niklasnatter** [comment] 2021-03-04 09:34
Thats good to hear 🙂  
Closing this as solved then - feel free to create a new issue if you encounter another problem

**Closed as completed by niklasnatter** 2021-03-04 09:34 UTC
Labels: Bug
