### ISSUE TITLE
Category content type adaption

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3413] opened 2017-06-21 08:45 UTC
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | --
| Browser Version | --

#### Actual Behavior

No parameters available for content type category.

#### Expected Behavior

Following things would be great:
* Root key (to limit a categories)
* Min occurs
* Max occurs

**Comment by danrot** [comment] 2019-11-21 16:03
Duplicate of #2938.

**Closed by danrot** 2019-11-21 16:03 UTC
