### ISSUE TITLE
Documentation custom controller for existing content

### ISSUE THREAD

**Issue by almare** [sulu/sulu#5474] opened 2020-08-31 15:13 UTC
# Problem description
I tried to find some documentation "How to build a custom controller". I found some documentations, but they are all about a new custom entity. In my case I don't want to create a new entity to reduce the overhead of coding. This was the main reason for choosing sulu at the time I started using sulu. The most things could be done, by xml and twig. 
Now I reached a point where the need of some custom coding grows. 

It would be nice if you could add a docu with the topic custom controller and already existing content created by the xml configurations.

My use cases:

1. I created a page content type called: "jobs". My goal was to create a simple listing controller for all my active jobs.
2. I have also another page content type called: "plugin". Here is my goal to make a listing of all plugins which had the attribute "roadmap_current" filled out. The aim is get a listing with only the plugins which had a not empty attribute.

Topics of the docu could be:
- Get a paginated list of all active jobs
- Ordering of the result
- Filter jobs by attached properties
- How to add a navigation menu entry for the custom controller

As i started this task looks really simple to me as, but at the moment it feels like that it took too much time to solve such a simple task. Maybe you could give me / us some hints.

Thank you

**Comment by alexander-schranz** [comment] 2020-08-31 15:42
You can define your own controller in your the `<controller>`  part of your `template.xml` and there you can call a service which will load your `jobs` or `plugins` from the database and then call the `renderStructure` Controller of the extended WebsiteController:

See for example the following:

https://gist.github.com/alexander-schranz/96eb3f61cad26ab6b74d#file-sulusimplerequestextendcontroller-php-L21-L29

If you want that a content manager can select specific jobs or plugins, you need to create a custom content type. In this case you don't need to touch anything on the controllers. If you want to create a smart content filter for your types have a look at https://docs.sulu.io/en/2.1/cookbook/smart-content-data-provider.html

**Comment by almare** [comment] 2020-08-31 15:58
Thank you for your answer and the links. I have not more specific needs. So I think I don't need a custom content type. At the moment I work with the smart content type, but I was not able to completely achieve my goal with the smart content type.

Do you have any advice regarding the service? I think I am completely responsible for the loading, translating, etc. of the data. Is there a base service class from which I can extend? I don't want to reinvent the wheel. I thought maybe I could add another where clause to the query to solve my problem.

Do you have any advice how to create the navigation menu? Will it appear once I add to the xml file. If yes how is the menu entry named?

**Comment by alexander-schranz** [comment] 2020-08-31 17:19
@almare

> Do you have any advice regarding the service? I think I am completely responsible for the loading, translating, etc. of the data. Is there a base service class from which I can extend? I don't want to reinvent the wheel. I thought maybe I could add another where clause to the query to solve my problem.

There is no simpler way creating a smart content provider as documented in the [docs](https://docs.sulu.io/en/2.1/cookbook/smart-content-data-provider.html). The base class is there the  `BaseDataProvider`.

The only simpler way is as written above avoid to create a smart content and just load your data inside a custom controller.

> Do you have any advice how to create the navigation menu? Will it appear once I add to the xml file. If yes how is the menu entry named?

As it is a normal page template you just create in the sulu admin tree a new page with that template and add it to the navigation. No more magic.

**Comment by nnatter** [comment] 2020-10-15 08:31
Hey,
I think your usecase can be solved by registering a custom `DataProvider` that can be used for the `smart_content`:
https://docs.sulu.io/en/2.1/cookbook/custom-page-data-provider.html

**Comment by nnatter** [comment] 2020-11-02 14:36
I hope the replies above answered your questions. I am going to close this as it is not a bug nor a feature request 🙂

**Closed by nnatter** 2020-11-02 14:36 UTC
Labels: Feature
